### ISSUE TITLE
Max height on the dialog does not work proper with IE 11

### ISSUE THREAD

**Issue by Kappadona** [dart-lang/angular_components#101]
If a max height is set on the dialog, the content within the dialog should be scroll-able if this height is reached. This works fine on Edge and Chrome, but on IE not. Also the example with max height on https://dart-lang.github.io/angular_components_example/#Dialogs does not work with IE.

![capture](https://user-images.githubusercontent.com/22842655/26866977-c47da9cc-4b63-11e7-95c8-e8cf7717a556.PNG)

 by adding one more line the footer disappear.

![capture1](https://user-images.githubusercontent.com/22842655/26866995-dba16b52-4b63-11e7-960a-1f7cc9c80a53.PNG)

**Comment by nshahan** [comment]
We don't have full support for IE. We are currently targeting the latest two versions of Chrome, Edge, Firefox, and Safari.

If there is a simple fix that would make it work without adding complexity to the component we can test it out and get it fixed.
