### ISSUE TITLE
Toolbars?

### ISSUE THREAD

**Issue by rickbsgu** [dart-lang/angular_components#103]
Any plans to put this in to match the material.io specs?

I'd vote for it.

**Comment by TedSander** [comment]
We'll have something, but we don't have any plans to release it in the near term. Should be later this year.

**Comment by thosakwe** [comment]
I have a package called `material_toolbar` that you might want to try:
https://github.com/thosakwe/material_toolbar

**Comment by TedSander** [comment]
Our solution has been released under the app_layout directory.
