### ISSUE TITLE
Support drag-n-drop in tree-view

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_components#105]
I saw the new tree-view component, but it doesn't look like it supports 
reordering items or moving items to different nodes using drag-n-drop (yet)

**Comment by TedSander** [comment]
Our UX doesn't have that in our spec, and we have no plans to support drag and drop in the tree.

**Comment by zoechi** [comment]
Sad. I had hoped the drag-n-drop from the reorder-list might make it into the tree-view. Would have made the tree-view much more valueable.
