### ISSUE TITLE
PopupDirective Event doesn't work

### ISSUE THREAD

**Issue by Kleak** [dart-lang/angular_components#107]
Seems like all the event we have access in the popup directive doesn't fire event.

**Comment by nshahan** [comment]
The various popup components have been refactored in the latest 0.6.0-alpha+2 update. Do you have a simple repro that we can test with to see if this is still an issue?

**Comment by Kleak** [comment]
i just started upgrade my app to angular 4, and i don't succeed to have a working popup with the new PopupSourceDirective.

he is what i have try and the error i get :
```html
<div popupSource #source="popupSource">
  <div class="more" [class.red]="post.showOptions" *ngIf="(post.showInfos || post.showOptions) && canShowMore" (click)="showPopup($event)">
    <kl-icon [icon]="iconMore" [fill]="moreColor"></kl-icon>
  </div>
</div>
<template popup [relativeTo]="source">
  ...
</template>
```

```
line 19, column 17 of AlPost: ParseErrorLevel.FATAL: Can't bind to 'relativeTo' since it isn't a known native property or known directive. Please fix typo or add to directives list.
[relativeTo]="source"
```

i have follow what is in the documentation of [PopupSourceDirective](https://github.com/dart-lang/angular_components/blob/master/lib/src/laminate/popup/src/popup_source_directive.dart#L17)

Is there something i do wrong ?

thanks

**Comment by Kleak** [comment]
i think this file is missing [popup directive](https://github.com/dart-lang/angular_components/blob/dedd4cb56dc931b76c282daa3c8f78856cb7e8ad/lib/src/laminate/popup/src/popup_directive.dart) 
Because now popup attribute is unknown.

**Comment by Kleak** [comment]
i have a repos where a really basic popup example is not working [here](https://github.com/Kleak/popup)

**Comment by Kleak** [comment]
is there a chance that popup, without material design spec, will be re-added into angular_component ?

**Comment by zacharydenton** [comment]
If you use <material-popup [hasBox]="false">, you'll get a popup without any material design.

**Comment by Kleak** [comment]
perfect thanks will update the example to test event this evening

**Comment by nshahan** [comment]
Feel free to reopen if you are still having issues.
