### ISSUE TITLE
Material-tree's expansion caret doesn't change if it starts with expandAll == true.

### ISSUE THREAD

**Issue by tonosama-atlacatl** [dart-lang/angular_components#111]
When I assign a variable that's equal to true to "expandAll", the expansion caret/button/glyph would not change after click, it remains stuck on the  ^ glyph. If such variable starts as false, the caret/button/glyph will change while opening/closing branches.

**Comment by nshahan** [comment]
A fix was landed in b8cbd19eab3cb7f89a5050d2320b1a68928f5e5d.
