### ISSUE TITLE
MaterialExpansionPanel expanded=true not working?

### ISSUE THREAD

**Issue by rafikiadmin** [dart-lang/angular_components#116]
It does not appear that the expanded=true input works. I tried expanded="true" and expanded=true and I tried with and without a Panel-Set wrapped around it.

**Comment by zoechi** [comment]
What about `[expanded]="true"`?

**Comment by rafikiadmin** [comment]
That did it. Thank you. I didn't think about that since the other values are working without brackets. Is there a pattern to when brackets are required and when not - or is it that brackets are always required/recommended, but that some patterns - like a directly set variable - that work without it?

**Comment by zoechi** [comment]
When you want to pass a string, xou can omit the brackets, in all other cases use them
I think it's a good idea to always use brackets when it's about passing values to Angular directives/components and omit them only if you want the attribute added to the DOM (for CSS or similar purposes).

**Comment by rafikiadmin** [comment]
Thank you. That is VERY helpful. I will close this issue.
