### ISSUE TITLE
Update pub version & documentation with material-tree

### ISSUE THREAD

**Issue by anands** [dart-lang/angular_components#117]
I see that [material-tree](https://github.com/dart-lang/angular_components/commit/4ffdf092a5007fbeb9a35b4d0ce1313e40942be8) has been added to the repo, but the [API ref](https://webdev.dartlang.org/components/api) and [pub version](https://pub.dartlang.org/packages/angular_components) were not updated with this change. Is this planned to some pub version release?

**Comment by adaojunior** [comment]
Seems like they just published to pub and it has also examples on the gallery.

**Comment by nshahan** [comment]
Yes, just published. Thanks! There is now a small example for Material Tree in the example gallery as well.
