### ISSUE TITLE
Provide an option to select the color of Glyph

### ISSUE THREAD

**Issue by Harikrishnadhas** [dart-lang/angular_components#123]
Currently there is no option to choose the color of an glyph. Hence all the glyphs are only coming in black. Please provide an option to code which color the glyph should appear.

ex
<glyph icon="add" color="darkgreen"></glyph>

**Comment by zoechi** [comment]
You can just use CSS for that

**Comment by Harikrishnadhas** [comment]
Let me try..

**Comment by Harikrishnadhas** [comment]
But that seems bit like an hack, but let me try.

**Comment by Harikrishnadhas** [comment]
I tried, but it doesn't work.

CSS:
.glyph_darkorange > i
{
    color:darkorange;
}

Template Code:
<glyph icon="person_add" class="glyph_darkorange"></glyph>

i have inspected the dom and seen that the actual icon is constructed using i tag inside glyph. When i set the color for i tag in the dom the color changes.

Through the CSS, though it is not working. Any other way to do?

**Comment by Harikrishnadhas** [comment]
It worked. I just set the color for the glyph and it did the magic. Trying to set the color to the child element in the simulated shadow DOMis not working (obviously).

**Comment by zoechi** [comment]
You can use `xxx ::ng-deep yyy {...}` to cross shadow DOM boundaries.

**Comment by TedSander** [comment]
To style a icon it should be as easy as:
```
<glyph icon="airline_seat_legroom_extra" class="blue-icon"></glyph>
.blue-icon {
  color: blue;
}
<!-- This also works -->
<glyph icon="airline_seat_legroom_extra" [style.color]="'blue'"></glyph>
```
We try to use CSS as much as we can for styling of all the components as it is the more natural fit, and is more performant.
