### ISSUE TITLE
please publish a version that accepts angular 4.0.0-alpha+1

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_components#127]

**Comment by nshahan** [comment]
Coming very soon. I am working on the export now.

**Comment by zoechi** [comment]
There is still a `@View()` annotation in the Modal component. 
Just discovered it with dependency_overrides. 
I guess you'd have found out anyway from the analyzer hints.

**Comment by nshahan** [comment]
Version 0.6.0-alpha+1 with a dependency on angular: 4.0.0-alpha+1 has been published.

I didn't see the annotation. Did it get cleaned up in the last sync?

**Comment by zoechi** [comment]
Yup, all seems working fine now.
