### ISSUE TITLE
Can't pub build/serve using 0.6.0-alpha

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular_components#128]
The AngularDart doc examples don't build with angular 4.0.0-alpha (see https://github.com/dart-lang/angular/issues/516), and so ACX 0.6.0-alpha, which is built on this version, isn't usable -- even with a dependency override.

The ACX pubspec currently reads:

```yaml
dependencies:
  angular: '4.0.0-alpha'
```

Could the angular dependency be change to

```yaml
dependencies:
  angular: ^4.0.0-alpha
```

or at least the **version upgraded to 4.0.0-alpha+1**?

cc @kwalrath @kevmoo @matanlurey

**Comment by zoechi** [comment]
Related to #127

**Comment by nshahan** [comment]
The update for 4.0.0-alpha+1 is coming very soon. I am reluctant to allow all versions of the alpha since there are some breaking changes expected.

**Comment by chalin** [comment]
Ok, thanks.

**Comment by nshahan** [comment]
Version 0.6.0-alpha+1 with a dependency on angular: 4.0.0-alpha+1 has been published.
