### ISSUE TITLE
Angular v4.0 - alpha, ngFor on material-expansionpanel causes hang

### ISSUE THREAD

**Issue by serates** [dart-lang/angular_components#131]
I am trying to do essentially:
```
<material-expansionpanel-set>
    <material-expansionpanel *ngFor="let x of list">...</material-expansionpanel>
</material-expansionpanel>
```

However on Angular v4.0-alpha and angular_components 0.6.0+1 this results in the page completely hanging for some reason, i have tried to use *ngFor on set itself and also hangs,

**Comment by serates** [comment]
This also seems to occur if i don't use the set and set expanded to true on all the panels.

**Comment by TedSander** [comment]
We're going to need more information as this simple example is working for me. I'm guessing it is actually your list implementation. If you remove material-expansionpanel entirely and use divs does it work?

If I had to guess I think your list object you are using isn't stable and changing or getting recreated on every digest loop which would cause the page to hang because you would be in an infinite loop.

**Comment by serates** [comment]
Yeah, it was a result of it rebuilding a list infinitely in the digest loop. I've employed the memoization cannon and it fixed the issue. Sorry for the fluff.

**Comment by Raker22** [comment]
I am having a similar issue. Using `*ngFor` on `material-expansionpanel` goes into an infinite loop but with `div` it works. I don't see any reason why the list would be rebuilding each digest cycle but I am relatively new to angular so if I missed something please let me know.

pets_component.html
```
<div id="pets_content">
  <div class="content">
    <material-expansionpanel-set>
        <material-expansionpanel *ngFor="let pet of pets" name="{{pet.name}}">
          <div>
            {{pet.name}} - {{pet.species}} - {{pet.breed}} - {{pet.dateOfBirth}}
          </div>
        </material-expansionpanel>
    </material-expansionpanel-set>
  </div>
</div>
```

pets_component.dart
```
@Component(
  selector: 'pets-view',
  styleUrls: const <String>['pets_component.css'],
  templateUrl: 'pets_component.html',
  directives: const <Object>[CORE_DIRECTIVES, materialDirectives]
)
class PetsViewComponent implements OnInit {
  Iterable<Pet> pets;

  @override
  void ngOnInit() {
    document.title = '$title - Pets';

    petService.list().then((Iterable<dynamic> pets) {
      this.pets = pets;
    });
  }
}
```

pet_service.dart
```
...

Pet parse(Map<String, Object> data) {
  return new Pet.fromMap(data);
}

...

Future<Iterable<dynamic>> list({Map<String, Object> query, bool parse = true}) async {
  final HttpRequest request = await HttpRequest.request(
    '$apiUrl/${this.url}${query == null ? '' : '?query=${JSON.encode(query)}'}',
    method: 'GET',
    requestHeaders: this.getHeaders()
  );

  this.handleError(request);

  Iterable<dynamic> result = JSON.decode(request.response);

  if (parse) {
    result = result.map(this.parse);
  }

  return result;
}

...

final PetService petService = new PetService();
```
