### ISSUE TITLE
Material Tab - Dynamic Issues

### ISSUE THREAD

**Issue by charliem** [dart-lang/angular_components#139]
The Material Tab Panel appears to break down if tabs are added or removed once it's been initialized. e.g. The tab components are generated inside an ngFor. When the underlying list is altered it can cause the control to throw exceptions. 

Specifically, if the active tab index is larger than the total number of tabs it fails.  I have a local fork so I can't send a straight pull request. However, the following changes below are fairly simple and seem to resolve the issues.

  ```
@ContentChildren(Tab)
  set tabs(QueryList<Tab> tabQuery) {
    _tabs = new List.from(tabQuery);
    _tabLabels = _tabs.map((t) => t.label).toList();
    _tabIds = _tabs.map((t) => t.tabId).toList();

    //FIXED: Check to make sure the active tab index is still valid
    if(_activeTabIndex >= _tabs.length)
      _activeTabIndex = _tabs.length - 1;

    // Setting the active tab needs to happen in the next turn as it is changing
    // the state of the tab.
    scheduleMicrotask(() {
      _setActiveTab(_activeTabIndex, false);
    });
```

```
void _setActiveTab(int i, bool focusTab) {

    //FIXED: To allow tabs to be dynamically removed
    if(activeTabIndex < _tabs.length)
      _activeTab?.deactivate();

```

**Comment by nshahan** [comment]
Does using `trackBy` as described get around the issue you are having? Similar to issue #18?

**Comment by nshahan** [comment]
Should be fixed in the last month, please reopen if you are still having issues.
