### ISSUE TITLE
Material icon

### ISSUE THREAD

**Issue by arcas0803** [dart-lang/angular_components#145]
I don't know why but glyph component shows the icon but material icon and material button with an icon inside don't show the icon. I have the link to the repository of material icon in the index.html.

**Comment by wstrange** [comment]
Make sure your component includes MaterialIconComponent  in the directives.

**Comment by nshahan** [comment]
True, make sure you have the right directives when you update from Glyph to MaterialIcon.

When you inspect, does the `<i>` element appear in the page where you expect it to be? Does it have the css property `font-family: 'Material Icons';`?

**Comment by nshahan** [comment]
I just realized that MaterialIconComponent and a few others are missing from the materialDirectives list. I will be adding them in the next release.

**Comment by kwalrath** [comment]
Timely. Today I was trying to update an example from glyph to material-icon, and wondering why it didn't just work...

**Comment by zoechi** [comment]
The Angular analyzer plugin shows such issues in the analyzer view. Highly recommended to use - works great ;-)

**Comment by kwalrath** [comment]
Closing, because `MaterialIconComponent` is in `materialDirectives` as of 0.6.0: https://webdev.dartlang.org/api/angular_components/angular_components/materialDirectives-constant
