### ISSUE TITLE
Release tags matching version, w/o leading "v"

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular_components#154]
Currently release tags are of the form vX.Y.Z, e.g. [v0.6.0](https://github.com/dart-lang/angular_components/releases/tag/v0.6.0). Might it be possible to drop the leading "v" and just use the package version?

This is a nit, but ACX is the only package we process under AngularDart docs (site-webdev), that doesn't use the packager version as the release tag. So scripts have to be coded with a special rule to handle this exception. 

cc @kevmoo @kwalrath

**Comment by kevmoo** [comment]
GitHub's own tagging suggestions say the `v` prefix is a good idea.

We are inconsistent across Dart repos, though...

![screen shot 2017-09-01 at 9 04 51 am](https://user-images.githubusercontent.com/17034/29978102-a907dce2-8ef4-11e7-9534-7d3334ebea1d.png)

**Comment by nshahan** [comment]
@kevmoo Are you saying we would we prefer to get the other repos converted to using the `v` in their tags?

**Comment by kevmoo** [comment]
Top priority: stay consistent. Do what the repo already does.
Next: I *think* it'd be good to standardize on vX.Y.Z for releases – since it follows the GitHub suggestion – but only for new repos

**Comment by nshahan** [comment]
OK, I will leave as is.
