### ISSUE TITLE
[Request for Components] Table & File Upload components 

### ISSUE THREAD

**Issue by nni123** [dart-lang/angular_components#155]
Hello,

Do you guys have any plan to include Table & File Upload components in the library? They are must to build enterprise or any decent level SPA webapps.

I don't see any milestone or roadmap for future builds.

I am coming from Java world and dart makes it easy to move into frontend space. I don't like Javascript & typescript. 

BTW: GWT was my choice but needs to move on.

**Comment by TedSander** [comment]
Hello @nni123,

Hopefully you're liking Dart. Our internal table infrastructure is quite complex and if we open source it it probably won't be this year. File upload we don't have anything we use commonly internally. I'm starting seeing movement on this, but no timeline, and again I don't think we will have anything this year.

**Comment by nni123** [comment]
@TedSander  I love dart & flutter. I am coming from Adobe Flex --> GWT & java back end. I hate JS & typescript/angular 4 make me sad (experience coder since 99). I hope Google put more resources into angular dart & flutter (developed sample mobile app in one hour can't believe it).

I think to make enterprise or mid-range application, we need data table & few other components for sure. Angular material two component library should be a good benchmark for angular dart. 

I am referring to another UI component library, which has angular dart data table & file upload components but not very well maintain.  

http://dart-league.github.io/ng_bootstrap/build/web/index.html

Thanks for your reply.
