### ISSUE TITLE
App Layout Drawer - Child List Items Flyout

### ISSUE THREAD

**Issue by NoahWilcox** [dart-lang/angular_components#156]
I am hoping to achieve a navigation layout similar to that of the GCP drawer where child items are inside of a flyout.

I'd be happy with anything that supports child elements right now. Although the flyout would be ideal, the Nested Navigation, Expanding navigation drawer, & Cascading navigation drawer (Desktop only) mentioned in the [material navigation patterns documentation](https://material.io/guidelines/patterns/navigation.html#navigation-patterns) would work too.

The flyout navigation I'm speaking of is below:

![23747d569](https://user-images.githubusercontent.com/7265591/30459143-762577b4-9974-11e7-95e8-1bfa2df7c150.png)

**Comment by TedSander** [comment]
We have the pieces built, but not all open sourced.

* Temporary Drawer - Exported
* Material List - Exported
* Material Menu - **TODO**

I'll see if we can get the menu for next quarter.

**Comment by nshahan** [comment]
Closing this issues since these components have since been released.
