### ISSUE TITLE
reorder-list item reordering doesn't work on mobile

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular_components#170]
E.g., try https://angulardart-org-dev3.firebaseapp.com/examples/web-angular (which is using version 0.7.1).

cc @kwalrath

**Comment by nshahan** [comment]
Duplicate of #19.

**Comment by chalin** [comment]
Well, not quite a duplicate of #19, given that it doesn't work under iOS either.

**Comment by chalin** [comment]
Maybe #19 needs to be slightly generalized?
