### ISSUE TITLE
form validation with material input

### ISSUE THREAD

**Issue by muzuro** [dart-lang/angular_components#178]
I am trying to implement form validation with input and button, here is template:

    <form #rForm="ngForm">
        <material-input label="Full name"
                        autoFocus floatingLabel
                        required
                        [(ngModel)]="fullName"
                        #name="ngForm">
        </material-input>
        <div>
            <material-button raised (trigger)="onSubmit()"
                             [disabled]="!rForm.valid">submit
            </material-button>
        </div>
    </form>

But after form opening button is enabled despite fullName is empty, [disabled]="!rForm.valid" don`t work. Is it wrong usage or may be a bug?

**Comment by muzuro** [comment]
I have added at bottom: `{{rForm.valid}}` - it is true, it seems like material-input don`t set form validity.

**Comment by TedSander** [comment]
[(ngModel)] only sets the value of a control it does not associate it with a form or control group.

You need to use ngControl to associate it with the form control itself. Something like:
```
<material-input label="Full name"
                    autoFocus floatingLabel
                    required
                    [(ngModel)]="fullName"
                    ngControl="name">
</material-input>
```

This will both setup the value of the control, and associate it with the form. ngControl will add it to the controls map of the form with the key `'name'`.
