### ISSUE TITLE
[Request] Support for angular 5.0.0-alpha and dart 2.0.0

### ISSUE THREAD

**Issue by 4cm4k1** [dart-lang/angular_components#179]
I started a new project, so I'm using the alpha and beta-stage SDK and packages (or as many as I can) instead of building and then waiting to refactor/upgrade. However, currently, angular_components doesn't support angular 5.0.0-alpha (and by extension dart 2.0.0).

Wondering if this could be added soon and/or whether that change would be non-trivial?

**Comment by nshahan** [comment]
The update is in the works and coming soon. Probably next week.

**Comment by 4cm4k1** [comment]
Awesome. And thanks for your great work!

**Comment by indiealexh** [comment]
Does v0.8.0 support angular 5?

**Comment by nshahan** [comment]
It does not include the latest sync of changes using 5.0.0-alpha features. I didn't update the dependency in the pubspec for that reason. I am working on that release now. 

That said, I experimented using a dependency override for `angular: 5.0.0-alpha` and I haven't noticed any issues.

**Comment by indiealexh** [comment]
Thanks @nshahan

**Comment by nshahan** [comment]
The version that supports angular: 5.0.0-alpha has been published. https://pub.dartlang.org/packages/angular_components/versions/0.9.0-alpha
