### ISSUE TITLE
Clear button does not work with Multi Selection on AutoSuggestInputComponent

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular_components#185]
I found this within my project, but you can reproduce in the gallery:

https://dart-lang.github.io/angular_components_example/#AutoSuggestInput

Click *Show clear icon*
Choose some options within *Multi Selection* combo.
Click the *clear* button.
Nothing happens.

**Comment by jodinathan** [comment]
With allowMulti true or false, the clear event is called. 
However, as said above, only when allowMulti is false that the selectedValues are cleared.

**Comment by TedSander** [comment]
cc @cissyshi

**Comment by cissyshi** [comment]
Auto suggest input only clears entered text when the clear icon is clicked. However we do expose a 'clear' output stream that you can listen to and do more.

**Comment by jodinathan** [comment]
@cissyshi, got it.
However, the button does look like a clear-selection button instead of a clear text.
