### ISSUE TITLE
MaterialExpansionPanel mixins are not working as expected.

### ISSUE THREAD

**Issue by rwrozelle** [dart-lang/angular_components#191]
I'm trying to use mixins for the MaterialExpansionPanel.

To test, I've taken the example code and added sass-builder, then I added an material_expansionpanel_demo.sccs file containing:

```
@import 'package:angular_components/css/material/material';
@import 'package:angular_components/material_expansionpanel/mixins';

@include expansionpanel-no-content-margin();
@include expansionpanel-header-min-height(28px, 28px);
```

It behaved as follows:
1.  When panel is closed, it is 28px height.
2.  When panel is open, it reverts to 64px height, expecting 28px.
3.  content wrapper margin is unchanged.

![material-expansion-panel-1](https://user-images.githubusercontent.com/8890259/32850620-a6df4e0e-ca00-11e7-9c8a-59c630a3ca1d.jpg)

![material-expansion-panel-2](https://user-images.githubusercontent.com/8890259/32850621-a6f3f8a4-ca00-11e7-933c-3b4cb615c3df.jpg)

![material-expansion-panel-3](https://user-images.githubusercontent.com/8890259/32850622-a706be80-ca00-11e7-967b-6ebc81d76ea7.jpg)

**Comment by nshahan** [comment]
It looks like the styles are being applied but your specificity isn't high enough so the default styles are overriding.

Does it work if you add a class to the panels you want to target with this style?

```
.my-panel {
  @include expansionpanel-no-content-margin();
  @include expansionpanel-header-min-height(28px, 28px);
}
```

**Comment by rwrozelle** [comment]
Yes, that resolves the issues.

**Comment by rwrozelle** [comment]
Also, how would I change the border color?

**Comment by nshahan** [comment]
I believe the border is defined by the spec here and we don't have a way to customize the color at the moment. 
https://material.io/guidelines/components/expansion-panels.html#expansion-panels-usage

@phantomesse Any clarifications?

**Comment by rwrozelle** [comment]
Thanks for pointing the spec out.

**Comment by phantomesse** [comment]
That's correct; we don't currently expose a way to custom the border color since the material expansion panel is designed according to the material spec.
