### ISSUE TITLE
Meta Issue: Roadmap - Q4

### ISSUE THREAD

**Issue by nshahan** [dart-lang/angular_components#193]
## Current Projects - Q4
We schedule our work a quarter at a time. Here is what we are working on right now.

### Open source our component gallery generator.

* Replace the existing angular_components_example repo with an improved gallery built with the generator.
* The new gallery should be easier to browse and have additional examples for many components.

### Release all usage examples that we use in our gallery generator.

* Add our internal usage examples to this repo.
* Add tools to build individual examples or a gallery of all available components locally.

### Add new components.

* Material Menu
* Material Datepicker

**Comment by supermuka** [comment]
Hi,
Would it be possible to know  (deadline) when we will get more Angular Dart Components (Cards, Data table, an others) like Js has: https://material.angular.io/components/?

**Comment by arcas0803** [comment]
Any progress on this. We are in q1. Is It possible to update roadmap ?

**Comment by nshahan** [comment]
Menu was released in version 0.9.0-alpha+1. The other tasks are still in progress and carried over into Q1.

Created new roadmap issue for Q1 2018 #221.
