### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/angular_components#195]
- [ ] Remove the `preview` header. These are in good shape.
- [ ] Mention `material` in the first 1-2 sentences. So our search engine picks it up.
- [ ] Reword the `small fragment bits`

**Comment by mit-mit** [comment]
I think you are also missing the word 'angular' (only have angulardart)

**Comment by nshahan** [comment]
Fixed in ca51ddf53c7570203c4bebe7fee707a88ae1b30e.
