### ISSUE TITLE
pub build --mode=debug hangs

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular_components#198]
Running `pub build --mode=debug` locally on an example app hangs, whereas `pub build` terminates successfully in less than 40s when run on the same example.

To reproduce this issue, follow these steps:

- **Download** a [zip of the site-webdev project from the **5-dev branch**](https://github.com/dart-lang/site-webdev/archive/5-dev.zip),<br>unzip, and<br> cd to the repo root. 
- <code>cd <a href="https://github.com/dart-lang/site-webdev/tree/master/examples/ng/doc/template-syntax">examples/ng/doc/template-syntax</a></code>
- `pub upgrade`
- `pub build --mode=debug -v`

This results in the following output:

```nocode
template-syntax > pub build --mode=debug -v
FINE: Pub 2.0.0-dev.8.0
IO  : Deleting directory build.
FINE: Loading asset environment...
FINE: Initializing barback...
FINE: Serving packages on localhost:0.
MSG : Loading source assets...
FINE: Providing sources for template_syntax|lib.
FINE: Loading source assets finished (0.028s).
FINE: Provided sources.
FINE: Loading transformers...
FINE: Transformer dependencies:
    | angular: -
    | test/pub_serve: -
    | dart_to_js_script_rewriter: -
FINE: Using cached transformer snapshot.
MSG : Loading angular, test/pub_serve and dart_to_js_script_rewriter transformers...
FINE: Loading transformers from [angular, test/pub_serve, dart_to_js_script_rewriter]
FINE: Spawning isolate from ./.pub/transformers/transformers.snapshot.
FINE: Loading angular, test/pub_serve and dart_to_js_script_rewriter transformers finished (0.103s).
FINE: Transformers from angular: {group of [[BuilderTransformer: Instance of 'TemplatePlaceholderBuilder'], [ReflectionRemover], [BuilderTransformer: Instance of 'StylesheetCompiler', BuilderTransformer: Instance of 'LibraryBuilder']]}
FINE: Transformers from test/pub_serve: {PubServe}
FINE: Transformers from dart_to_js_script_rewriter: {DartToJsScriptRewriter}
FINE: Loading transformers finished (0.428s).
FINE: Initializing barback finished (0.482s).
FINE: Loading asset environment finished (0.648s).
MSG : Building template_syntax...
FINE: Providing sources for template_syntax|web.
FINE: Bound "web" to localhost:0.
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on template_syntax|primary]:
    | Took 0.4s (0.0s awaiting secondary inputs).
FINE: [Fine from BuilderTransformer: Instance of 'StylesheetCompiler' on template_syntax|primary]:
    | Took 0.6s (0.0s awaiting secondary inputs).
FINE: [Fine from BuilderTransformer: Instance of 'LibraryBuilder' on template_syntax|primary]:
    | Not yet complete after 10.0s
FINE: [Fine from BuilderTransformer: Instance of 'LibraryBuilder' on template_syntax|primary]:
    | Not yet complete after 20.0s
FINE: [Fine from BuilderTransformer: Instance of 'LibraryBuilder' on template_syntax|primary]:
    | Not yet complete after 30.0s
FINE: [Fine from BuilderTransformer: Instance of 'LibraryBuilder' on template_syntax|primary]:
    | Not yet complete after 40.0s
...
FINE: [Fine from BuilderTransformer: Instance of 'LibraryBuilder' on template_syntax|primary]:
    | Not yet complete after 2:12.0s
FINE: [Fine from BuilderTransformer: Instance of 'LibraryBuilder' on template_syntax|primary]:
    | Not yet complete after 2:22.0s
...
```

Btw, I need to build in debug mode to run component tests using `angular_test`.

Version info:

- Angular 5.0.0-alpha+1
- angular_components 0.9.0-alpha+1
- SDK 2.0.0-dev.8.0
- MacOS 10.13

cc @matanlurey @kwalrath

**Comment by nshahan** [comment]
I followed these steps and it built on my system without running into this problem.

System:
* MacOS 10.12.6 (16G1036)
* SDK 2.0.0-dev.8.0

This is the behavior that I have been seeing lately. I find that any tiny change to the package or it's dependencies including where you are getting the dependencies from (dependency override to a local path or git repo) can make the issue disappear. It is also hard to replicate it on different machines.

**Comment by chalin** [comment]
I can confirm that under MacOS 10.12.6 `pub build --mode=debug` runs w/o problems. Might you have access to a MacOS 10.13 machine to try it out?

**Comment by chalin** [comment]
> I find that any tiny change to the package or it's dependencies ... can make the issue disappear.

Yes, I can confirm that too! The problem has gone away now, after having done a `pub upgrade`, which picked up a few new package versions.

**Comment by nshahan** [comment]
I'm going to close this issue because it was so intermittent that we could not find a reasonable solution and we just published the first version that no longer supports building with pub transformers.

Now we use `pub run build_runner build` .
