### ISSUE TITLE
Remove MaterialButtonBase from materialDirectives list

### ISSUE THREAD

**Issue by wem** [dart-lang/angular_components#199]
The analyzer plugin marks any usage of the materialDirectives list within component annotations as error because MaterialButtonBase is not a "real" directive.

**Comment by nshahan** [comment]
Can you provide more details about which plugin and version along with the steps to reproduce the error that you are seeing?

I don't see this error in intelliJ with ver 172.3968.27 of the Dart plugin.

**Comment by wem** [comment]
IDEA Dart plugin: 172.4343.25
Dart version: Dart VM version: 2.0.0-dev.8.0 (Fri Nov 17 21:56:10 2017) on "linux_x64"
angular_analyzer_plugin: 0.0.11
angular_components: 0.8.0 or 0.9.0-alpha+1

analysis_options.yaml:
analyzer:
  strong-mode: true
  plugins:
    angular:
      enabled: true

Steps to reproduce:
1. Create a AngularDart project from scratch with stagehand
2. Activate the analyzer in the analysis_options.yaml as shown above: [plugin doc](https://github.com/dart-lang/angular_analyzer_plugin)
3. Restart analysis server
4. After that any usage of materialDirectives will be shown as error.

![analsis_error](https://user-images.githubusercontent.com/1784773/33420117-b264949c-d5ad-11e7-9956-ef501a3528a3.png)

**Comment by nshahan** [comment]
Thanks! I make sure to get it removed from the helper list of directives.

**Comment by nshahan** [comment]
Fixed in #203.
