### ISSUE TITLE
material-tab labels

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular_components#200]
At the moment material tabs only allow labels to be text Strings. Why not use ng-content selectors to allow for more complex labels so you could do something like this:

```
<material-tab>
 <div tab-label>
  <glyph icon=“location_on” *ngIf=“smallScreenDevice"></glyph>
  <template [ngIf]=“!smallScreenDevice”>Location</template>
 </div>
 <div tab-content>
    location stuff
  </div>
</material-tab>
```

This would allow people to create designs shown in the official material design documents such as:
![components-tabs-usage-mobile7](https://user-images.githubusercontent.com/298850/33831229-1d82fd26-de6f-11e7-960a-31f471e6316b.png)

**Comment by jimmyff** [comment]
Or as people are 99.9% of the time only ever going to way labels & icons, you could just add `icons` as an input and then have a way of telling the material-tab-strip to display only labels, only icons or both?

```
      <material-tab-strip
          [tabLabels]="tabLabels"
          [tabIcons]="tabIcons"
          showLabels="false"
          showIcons="true"
      ></material-tab-strip>
```

**Comment by furrary** [comment]
Duplicate of https://github.com/dart-lang/angular_components/issues/70

**Comment by jimmyff** [comment]
oh, sorry for the dupe - i thought I'd already opened a ticket somewhere for this but couldn't find it on the issue tracker.

**Comment by jimmyff** [comment]
If I add `icon` as an Input for `TabButtonComponent` and add `tabIcons` as an Input for `FixedMaterialTabStripComponent`, would you accept a PR? cc: @nshahan

**Comment by nshahan** [comment]
We probably don't want to add it there to keep the fixed tab strip as lightweight as possible. We have a task in our list to eventually add a customizable wrapper arround fixed tab strip that everyone could use for their own needs.

**Comment by jimmyff** [comment]
duplicate of #70
