### ISSUE TITLE
material-dropdown-select scrolling back to first selected

### ISSUE THREAD

**Issue by logangorence** [dart-lang/angular_components#204]
I'm porting a project from Polymer.dart to AngularDart, and I'm having an issue where a material-dropdown-select with multi-select on is scrolling to the first selected option. I'm fairly new to web development, and this could easily be a mistake on my part, but I've tried changing how I've done it to no avail.

I have a mockup live at https://logangorence.github.io/get-dsa/, and the DSLinks dropdown is the one that shows my problem. If anyone could help in fixing this, that would be great.

**Comment by nshahan** [comment]
I see the same behavior in your example, not sure what the cause might be. Are you triggering any extra events when the mouse moves out of the popup?

Take a look at the example page
https://dart-lang.github.io/angular_components_example/#Selects

And the code for the example
https://github.com/dart-lang/angular_components_example/tree/master/lib/src/material_select_demo

Compared to the example are you doing any extra work?

**Comment by logangorence** [comment]
I'm not triggering any events with the mouse, and I want to try adding more options to the Components Examples page to see if it exists there. The only difference between my code and the example is in the constructor I am loading a external file containing all of the data and then populating the List of OptionGroups with the specific options in each group. I'm attaching the relevant code below.

```html
<material-dropdown-select
                [buttonText]="selectedLinksLabel"
                [options]="links"
                [selection]="selectedLinks">
</material-dropdown-select>
```

```dart
  static List<OptionGroup<Option>> _links = [];
  SelectionModel<Option> selectedLinks = new SelectionModel.withList(allowMulti: true);
  SelectionOptions<Option> get links => new SelectionOptions.withOptionGroups(_links);
  String get selectedLinksLabel => "${selectedLinks.selectedValues.length} links selected";
```
```dart
loadLinks().then((l) {
      linkModels.addAll(l.map((x) => new DSLinkModel(x)));
      linkModels.sort((a, b) => a.displayName.compareTo(b.displayName));
      linkModels.forEach((x) {
        var category = x.category;

        if (!_links.any((x) => x.uiDisplayName == category)) {
          _links.add(new OptionGroup<Option>.withLabel([], category));
        }

        var optionGroup = _links.firstWhere((x) => x.uiDisplayName == category);
        optionGroup.add(new Option(x.name, x.displayName));
      });
});
```dart
class Option implements HasUIDisplayName {
  final String code;
  final String label;

  const Option(this.code, this.label);

  @override
  String get uiDisplayName => label;

  @override
  String toString() => uiDisplayName;
}
```

**Comment by nshahan** [comment]
My guess is that the SelectionOptions is getting recreated each change detection cycle and each group is being recreated inside. Try initializing the SelectionOptions once instead and returning it instead of creating a new one each time. 

I'll take another look at our examples and see if they need some updating for best practices.

**Comment by logangorence** [comment]
Yep, that works perfectly. I don't believe the examples have anything wrong with them, but I must have just written the code not thinking about it and when it worked I probably didn't think about that line of code. Thanks a ton! 😃
