### ISSUE TITLE
material-css broke angular componets default style

### ISSUE THREAD

**Issue by redradist** [dart-lang/angular_components#206]
When I am adding styles from **material-css** it broke default styles of **angular componets** for example **material-input**.

Is there possibility to coexist these two ? Maybe in **material-input** all styles should be marked as an **important** ?
Both AngularDart and MaterialCSS supported by Google I thought it should be able to coexist ...
If I apply Bootstrap it works nicer, all angular componets looks as before almost ... )

**Comment by nshahan** [comment]
We don't really want prevent users from modifying the style of a component. If I understand your request I believe it would break the mixins that we provide to override the default styling of the components.

I'd recommend against using styles that target across your entire application. We keep ours localized to the component to prevent this type of interference with other styles on the page.

We communicate with the UX team designing the material components for web for consistent styling but don't expect both sets of widgets to be used together.

**Comment by TedSander** [comment]
Angular itself has encapsulation for styles that are added using their system. This allows for styling to co-exist and means that you shouldn't need things like !important. Using !important would break theming, and wouldn't allow customizations for individual instances of the component.

You can use material-css but you would need to in a piecewise fashion, not in a 'bootstrap' way. If you added the specific CSS/Sass components in the styleUrls attribute you can get the material-css in an encapsulated way.

Working with any global 'bootstrap' type CSS style isn't going to work with angular_components as having global styles is a sledge hammer which is going to affect any DOM on the page. It is virtually impossible to know what is being overridden by the external source, and would be a never ending battle to ensure they don't conflict. You may see us use more of the material-css in our components, but it would be using the piecewise method described above, not the bootstrap.

**Comment by redradist** [comment]
Okay, in this case are there any default styles (provided by framework itself [**AngularDart**]) that I can use to customize **AngularDart** application ?
If no it means that better to use components provided by **Material-CSS** or **Bootstrap** in **AngularDart** for more consistent styles of application

**Comment by TedSander** [comment]
What styling are you looking for?

https://github.com/dart-lang/angular_components/blob/master/lib/css/material/const/_typography.scss has the font styling, but doesn't default them to any selectors.

**Comment by redradist** [comment]
I am looking for CSS Frameworks like Bootstrap or Material-CSS to make responsive Web App with AngularDart

**Comment by TedSander** [comment]
Like I said previously we don't have a global CSS like bootstrap or material-CSS. We do have app layout and that is done with https://github.com/dart-lang/angular_components/blob/master/lib/app_layout/README.md

If these don't work for you and bootstrap or Material-CSS get you what you are looking for I suggest going those directions. Also to make sure we are talking about the same thing I couldn't find a material-css project. The google supported CSS solution is here: https://material.io/components/web/

Which as far as I know should interoperate because it uses very specific selectors/class names for it's CSS.

**Comment by redradist** [comment]
@TedSander I will read README. Thank you for support !!
To be more presice I meant [](http://materializecss.com/) powered by Google

**Comment by TedSander** [comment]
Ahh materializecss is actually done by a team from Carnegie Mellon University http://materializecss.com/about.html and isn't affiliated with google at all to my knowledge.

I don't see us supporting that or bootstrap officially in any way. If we did support something more fully it would be mcw which I linked above.

**Comment by redradist** [comment]
@TedSander It is very strange, because About says:

> Created and designed by Google, Material Design is a design language that combines the classic principles of successful design along with innovation and technology. Google's goal is to develop a system of design that allows for a unified user experience across all their products on any platform.

**Comment by TedSander** [comment]
@redradist They are talking about Material Design not about the product itself.

**Comment by redradist** [comment]
@TedSander Oh, sorry I have confused. Yes, you are right
