### ISSUE TITLE
Can't generate dartdoc for v0.9.0-alpha+2 due to analysis errors

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular_components#207]
Here is the log output.

```nocode
acx > pub global run dartdoc --output doc/api
Generating documentation for 'angular_components' into /Users/chalin/git/dart/angular_components/doc/api/
parsing lib/angular_components.dart...
...
parsing lib/utils/rate_limit_utils/rate_limit_utils.dart...
parsing lib/utils/strings/string_utils.dart...
parsing /opt/homebrew/Cellar/dart/2.0.0-dev.15.0/libexec/lib/_internal/js_runtime/lib/interceptors.dart...
analysis errors from source: package:angular_components/mixins/highlight_assistant_mixin.dart (/Users/chalin/git/dart/angular_components/lib/mixins/highlight_assistant_mixin.dart
[error] Target of URI hasn't been generated: 'package:angular_components/highlighted_text/highlighted_value.template.dart'. at lib/mixins/highlight_assistant_mixin.dart, line 7.

Generation failed: encountered 1 analysis error.
```

But the [analysis_options.yaml](https://github.com/dart-lang/angular_components/blob/master/analysis_options.yaml) file contains:
```yaml
analyzer:
  strong-mode: true
  errors:
    ...
    uri_has_not_been_generated: ignore
```

I'm using:
- SDK 2.0.0-dev.15.0
- Dartdoc 0.15.0+1

cc @kwalrath @jcollins-g

**Comment by nshahan** [comment]
We are facing a similar problem with the pana package that analyzes and scores the packages for pub.dartlang.org. https://github.com/dart-lang/pana/issues/213 

Maybe there is a common solution we can agree on in both cases.

**Comment by alorenzen** [comment]
This _should_ be fixed by the switch to `build_runner`. I believe analyzer will eventually know how to work with those generated files, just like it does internally.

The problem is that with transformers, those files don't actually exist anywhere that the analyzer can use.

**Comment by nshahan** [comment]
@chalin As a temporary workaround you can insert the line `// ignore: uri_has_not_been_generated` in `lib/mixins/highlight_assistant_mixin.dart` above the import of the `template.dart` file.

Then you can successfully run Dartdoc locally.

**Comment by chalin** [comment]
Good idea, I'll do that. Thanks.

**Comment by jcollins-g** [comment]
dart-lang/dartdoc#1586 is related to this as we don't interpret analysis options because we're not on the analysis driver yet.  This is the next big piece of dartdoc work though.

**Comment by kevmoo** [comment]
Could we find a way to (optionally) ignore this error? https://github.com/dart-lang/dartdoc/issues/1595

By just commenting out the throw in DartDoc, I was able to generate the docs for components pretty easily

**Comment by chalin** [comment]
@nshahan - FYI, adding `// ignore_for_file: uri_has_not_been_generated` to `lib/mixins/highlight_assistant_mixin.dart` doesn't help. Dartdoc still reports an error.

**Comment by jcollins-g** [comment]
If the docs generated are reasonable without the error dartdoc can be made to ignore it.   This probably requires inspection; dartdoc itself might not be able to tell that it went off the rails, especially outside of checked mode.

**Comment by chalin** [comment]
My guess is that the resulting docs should be ok. I'm willing to do the required manual inspection if you'd like to put ignoring that error behind a flag.

**Comment by chalin** [comment]
> If the docs generated are reasonable without the error dartdoc can be made to ignore it.

Doc generation seems to proceed now (under SDK 2-dev.24) even when the error is present. The generated docs seem fine.
