### ISSUE TITLE
Input - Glyph and Text alignment coupled

### ISSUE THREAD

**Issue by sudolibre** [dart-lang/angular_components#209]
In the example for adding a trailingGlyph you add a glyph and set the rightalign property to true. This moves the glyph to the right but also causes the text to populate from the right as well (like you would expect for hebrew or arabic). These should be two separate things.

This is required for the common use case of creating a visibility icon on the right of a password field to toggle masking of the entered text.

**Comment by TedSander** [comment]
Trailing glyph is what puts the glyph on the right side of the input not the right align property these two should already be separate. Have you tried just setting the trailing glyph and not using right align? Does that satisfy your use case?

**Comment by sudolibre** [comment]
I just tried and it and it seems to work fine. If I recall correctly the first time I tried this it put the glyph right in the center of the input field. Then I saw the example used right align so added that. I'll close this and see if the angular_components_examples team agrees right align should be taken out of the example for trailing glyph.
