### ISSUE TITLE
material-dropdown-select css width no effect on 0.9.0-alpha+3

### ISSUE THREAD

**Issue by joo** [dart-lang/angular_components#213]
`material-dropdown-select {
    width: 100px;
}`

**Comment by joo** [comment]
Everything works fine at 0.8.

**Comment by joo** [comment]
css width no effect, when material-dropdown-select options is empty.
but, works fine at 0.8.

**Comment by TedSander** [comment]
Sorry I'm going to need some more context as I can't reproduce this error. 

Here is my Sass file:
```css
material-dropdown-select { width: 100px; }
```

And Component:
```dart
@Component(
  selector: 'material-dropdown-select-demo',
  providers: popupBindings,
  directives: const [
    MaterialDropdownSelectComponent,
  ],
  templateUrl: 'material_dropdown_select_demo.html',
  styleUrls: const ['material_dropdown_select_demo.scss.css'],
)
```
Which produces:
<img width="1118" alt="screen shot 2018-01-24 at 3 48 06 pm" src="https://user-images.githubusercontent.com/5643740/35363308-3cb6dad8-011e-11e8-82a1-61bd972aa469.png">

**Comment by joo** [comment]
Thanks @TedSander ,  I will test more.

**Comment by joo** [comment]
Thanks @TedSander , you are right.

**Comment by supermuka** [comment]
@joo, did you get the `width` working on `material-dropdown-select`? If yes, how? 
For me, changing the `width` has no effect too.
