### ISSUE TITLE
Material ExpansionPanel Set - Designate starting panel AND still have one panel open at a time.

### ISSUE THREAD

**Issue by rafikiadmin** [dart-lang/angular_components#223]
Unless there is something I am missing, it seems that EXPANDED=true on an ExpansionPanel makes a panel open by DEFAULT (as expected), but if that panel is in a Panel Set that panel does not CLOSE when another panel is open (not expected).

The exception to this pattern is if the User CLOSES the initially opened panel specifically, then the set starts working like normal from that point forward.

I think the behavior that would be the most consistent would be for EXPANDED=true to follow the PanelSet pattern if the panel is part of an "accordion" panel set. If a developer wants always opened (yet closable) panels, those can be coded outside of a Panel Set.

**Comment by nshahan** [comment]
I don't see this when I try it. What do you mean by EXPANDED=true? Can you share a code snippet?

This template works for me as you would expect.
```html
  <material-expansionpanel-set>
    <material-expansionpanel name="Panel 1">
      Panel Text 111
    </material-expansionpanel>

    <material-expansionpanel name="Panel 2">
      Panel Text 222
    </material-expansionpanel>
    <material-expansionpanel name="Panel 3"
                             [expanded]="true">
      Panel Text 333
    </material-expansionpanel>
  </material-expansionpanel-set>
```

**Comment by rafikiadmin** [comment]
I am just getting back to this - a very busy couple days. Your template sample is exactly the scenario I am describing. So, I was trying to do a completely isolated experiment and I just realized, embarrassingly, that I don't think our Pub Dependencies were set to get the latest version of the component code. So, as soon as I can (within the next 24 hours), I will try again. I suspect we can close this issue as something that was maybe resolved long ago. Sorry, again.

**Comment by rafikiadmin** [comment]
Ok. I tried this with the newest stable everything and my observations are the same. (And I used your exact code just to be sure I was not doing something funny. So, let me explain my request.  First, let me say that nothing is technically "broken", it is just that this does not function the way I THINK it should function from my understanding. So, perhaps this is a feature request, not an issue. You can decide.

My understanding is:
ExpansionPanels in the template as individual items open and close independently.
ExpansionPanels wrapped in an ExpansionPanel SET work together and only ONE panel opens at a time. (i.e. the SET modifies the behavior of the individuals PANELS)

What I see is that when [expanded]="true" is set on an expansionpanel, that panel is open on load, but if it is inside an ExpansionPanel SET, it does not close when another expansionpanel in the set is opened, and that seems like the expected behavior to me.

If the user specifically closes it, then it begins working with the other expansionpanels as expected. (i.e. closing when another panel is opened)

I hope that makes sense.

**Comment by nshahan** [comment]
@phantomesse Any thoughts here?

**Comment by phantomesse** [comment]
Hi @rafikiadmin! Sorry for the delay. I tried Nicholas's example and the panels behaved as expected. Panel 3 is initially expanded and when I click on Panel 1 or Panel 2, Panel 3 collapses. Can you post the code that you're having trouble with? Thanks!

**Comment by rafikiadmin** [comment]
Interesting. I just tried again and I got the same thing. I have tried to build a barebones app. Here is the code:

main.dart:
void main() {
  bootstrap(AppComponent);
}

App_Component.dart:
import 'package:angular/angular.dart';
import 'package:angular_components/angular_components.dart';
@Component(
  selector: 'my-app',
  styleUrls: const ['app_component.css'],
  templateUrl: 'app_component.html',
  directives: const [materialDirectives],
  providers: const [materialProviders],
)
class AppComponent {

}

App_Component.html:
<material-expansionpanel-set flat>
    <material-expansionpanel flat name="Panel 1">
        Panel Text 111
    </material-expansionpanel>

    <material-expansionpanel flat name="Panel 2">
        Panel Text 222
    </material-expansionpanel>
    <material-expansionpanel flat name="Panel 3"
                             [expanded]="true">
        Panel Text 333
    </material-expansionpanel>
</material-expansionpanel-set>

**Comment by rafikiadmin** [comment]
App_Component.html did not paste correctly:
<material-expansionpanel-set flat>
    <material-expansionpanel flat name="Panel 1">
        Panel Text 111
    </material-expansionpanel>

    <material-expansionpanel flat name="Panel 2">
        Panel Text 222
    </material-expansionpanel>
    <material-expansionpanel flat name="Panel 3"
                             [expanded]="true">
        Panel Text 333
    </material-expansionpanel>
</material-expansionpanel-set>

**Comment by rafikiadmin** [comment]
APP_COMPONENT.HTML did not paste correctly before:

<material-expansionpanel-set flat>
    <material-expansionpanel flat name="Panel 1">
        Panel Text 111
    </material-expansionpanel>

    <material-expansionpanel flat name="Panel 2">
        Panel Text 222
    </material-expansionpanel>
    <material-expansionpanel flat name="Panel 3"
                             [expanded]="true">
        Panel Text 333
    </material-expansionpanel>
</material-expansionpanel-set>

**Comment by rafikiadmin** [comment]
Here are some screen shots. I have tried this in Chromium and Chrome.
Initial:
![image](https://user-images.githubusercontent.com/25962823/38995599-f1589844-43f1-11e8-8e7c-97b993d0c936.png)
When clicked on 2:
![image](https://user-images.githubusercontent.com/25962823/38995636-0a4fc52a-43f2-11e8-8d6c-5f7b1ec4ae7a.png)
When clicked on 1:
![image](https://user-images.githubusercontent.com/25962823/38995673-1f54f88c-43f2-11e8-84f1-bec4519a311a.png)

**Comment by rafikiadmin** [comment]
Panel 3 does not act normally UNTIL I click on it. Once I do, then the whole panel set works as expected.

**Comment by rafikiadmin** [comment]
And here is the relevant part of my pubspec.yaml:

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0

**Comment by nshahan** [comment]
Ah OK! That explains why we are seeing different behavior. I can confirm that I see the same issue that you do when using v0.8.0. It looks like this has been fixed already. When building with the later versions v0.9.0-alpha+x the expansion panels are working as expected.

**Comment by nshahan** [comment]
It is the version we use for our apps. There are more changes required though because of the migration to Dart 2 is in process. It only supports build_runner and the dev version of the SDK.

**Comment by rafikiadmin** [comment]
Yeah. I tried and realized that too much needs to change at the moment. I want to spend my time developing rather than figuring out logistics. I am sure these questions are now outside the scope of this issue/ticket, but I am wondering if there is a projection of when 0.9.0 will move out of Alpha and/or more specifically when there will be a new “automatic” setup like what I used in Webstorm/Idea that will get me the latest code without figuring out what all must change?  Or will there just be a jump to 2.0? And will that jump break much from 1.24?

**Comment by nshahan** [comment]
The alpha tag is mostly due to the rate of change coming from the dependencies and the SDK as the ecosystem migrates to Dart 2.

There was some work done to update the template used in the IDEs, but we are not ready to publish the updates yet since we don't want to force new users onto the alpha. You can see the template here: https://github.com/dart-lang/stagehand/tree/master/templates/web-angular
