### ISSUE TITLE
Material Input no good way to capture just `enter` event

### ISSUE THREAD

**Issue by NickWu007** [dart-lang/angular_components#226]
Hi,

I am using `MaterialInput` in my project and surprised that there doesn't seem to be a good way to capture user pressing the `enter` key only.

There are 2 output events relevant for this. `inputKeyPress` doesn't even fire when the enter key is pressed, so clearly no good. 

On the other hand, `change` does fire when the enter key is pressed, but it also fires when the input field losses focus. What happens a lot in my use case is the user types something in, and then leaves the input field to select some other texts to copy over. But at that point the `change` event would have fired and the partially inputted text were processed, which is not ideal.

Been going through the doc and experimenting with different ways but haven't gotten anywhere. Any suggestion for this? Thanks in advance.

Nick

**Comment by nshahan** [comment]
I think the easiest solution is probably to just use the built in support from Angular.
https://webdev.dartlang.org/angular/guide/user-input

For example:
https://github.com/dart-lang/stagehand/blob/master/templates/web-angular/lib/src/todo_list/todo_list_component.html#L6
