### ISSUE TITLE
Material slider support

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/angular_components#227]
Angular components still don't have sliders. I have a 3 years old Polymer app that I cannot fully port to Angular

https://material.angular.io/components/slider/overview

**Comment by TedSander** [comment]
Thanks for pointing this out. We have one, and should be able to add it to open source pretty easily. cc: @nshahan

**Comment by nshahan** [comment]
Yes, it looks like this one wont take to much work for open sourcing. I'll get the process started.

**Comment by supermuka** [comment]
Great news! Coincidentally I was just today studying a way (light) to implement the Material Slider in Dart. Now I'm waiting for the open source version... ;)

**Comment by nshahan** [comment]
Added in [v0.9.0-alpha+10](https://pub.dartlang.org/packages/angular_components/versions/0.9.0-alpha%2B10).
