### ISSUE TITLE
Dropdown looks weird, arrow too low

### ISSUE THREAD

**Issue by alextekartik** [dart-lang/angular_components#228]
In the demo it seems the dropdown arrow is not aligned with the text (it seems a little bit too low). I thought it was a bug but it seems to still be the case:

https://dart-lang.github.io/angular_components_example/#Menus

Is this planned to change or is there a css solution to align the arrow properly with the text?

**Comment by TedSander** [comment]
@nshahan looks like the internal icons have some extra styling that is messing with the positioning here. The top and the position are set for those icons. I'm not sure why the material font team has it set internally, but not externally.

**Comment by nshahan** [comment]
Thanks for pointing this out. I'm testing a fix and will sync to this repo soon.

**Comment by TedSander** [comment]
Yes, but there is a patch you should be able to do locally.

In a component higher in the tree. Even possibly root you can override the CSS.

```css
::ng-deep glyph > i {
  top: -6px;
  position: relative;
}
```

Be careful with ::ng-deep as it is a pretty big hammer, but it should get you unblocked here.
