### ISSUE TITLE
Please release a version that uses  angular: 5.0.0-alpha+8

### ISSUE THREAD

**Issue by rwrozelle** [dart-lang/angular_components#235]
I'm having a problem with the build_runner.  It appears to be because the angular builder.dart file was using useAstPkg as a compiler flag in angular: 5.0.0-alpha+7.  This was fixed in +8 see https://github.com/dart-lang/angular/commit/5331aa6c9a209fc62e4cea4321246a1b09c84291.  I'm getting the following error:  

```
>pub run build_runner build
[INFO] Generating build script completed, took 745ms
'package:angular/builder.dart': error: line 29 pos 42: invalid arguments passed to constructor 'CompilerFlags' for class 'CompilerFlags': no optional formal parameter named 'useAstPkg'
const _defaultFlags = const CompilerFlags(
```
Thanks

**Comment by nshahan** [comment]
It is in progress. https://github.com/dart-lang/angular_components/pull/234

**Comment by nshahan** [comment]
Published.
