### ISSUE TITLE
material-drawer ng-content injection material-list not apply material-drawer style

### ISSUE THREAD

**Issue by joo** [dart-lang/angular_components#241]
```
    <material-drawer persistent #drawer="drawer">
        <div class="mat-drawer-spacer">
            <header class="material-header shadow">
                <div class="material-header-row">
                    <span class="material-header-title">test</span>
                </div>
            </header>
        </div>
        <ng-content select="material-list"></ng-content>
    </material-drawer>
```
above code, material-list and material-list-item not apply material-drawer material-list-item style.

**Comment by TedSander** [comment]
The way view encapsulation works is that a component can only affect the styling of their view elements. In this case anything in ng-content is in the parent's CSS context. Thus the styling will not be applied. That said we do support this, but the parent is the one that is going to need to apply the right style to the list. There is documentation about this in the README [here](https://github.com/dart-lang/angular_components/blob/master/lib/app_layout/README.md#navigation-styles). Last paragraph in that section.

**Comment by joo** [comment]
Thanks @TedSander.
