### ISSUE TITLE
Don't point people to pub-generated API docs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/angular_components#252]
As discussed in #242, the [pub-generated angular_components API docs](https://pub.dartlang.org/documentation/angular_components/0.9.0-alpha+10/) are confusing because they contain so many libraries (most of which have no description, to boot). It's OK to generate the API docs, and maybe they should be hosted on pub instead of [on webdev.dartlang.org](https://webdev-dartlang-org-dev.firebaseapp.com/api/angular_components), but we should encourage people to **use the docs in the gallery instead**. We can do this using the angular_components pubspec.yaml and README.

Some possible solutions:

* In the [angular_components pubspec.yaml](https://github.com/dart-lang/angular_components/blob/master/pubspec.yaml):
  * Keep the current homepage, but make docs point to the gallery: 
    * homepage: https://webdev.dartlang.org/components (works no matter what the version is)
    * documentation: https://dart-lang.github.io/angular_components_example
  * Make the gallery the homepage, make docs point to the API doc homepage on webdev:
    * homepage: https://dart-lang.github.io/angular_components_example
    * documentation: https://webdev.dartlang.org/api?package=angular_components **(this won't work until we switch the website to be v5)**
* In the [angular_components README](https://github.com/dart-lang/angular_components/blob/master/README.md):
  * Explicitly say that instead of using the auto-generated API docs, they should use the gallery, where they can see the running components and example code side-by-side. A screenshot of the gallery might be a good way to drive this home.
  * I could help with the README description.

/cc @chalin @kevmoo @TedSander @nshahan @isoos @jakobr-google @mit-mit @matanlurey

**Comment by nshahan** [comment]
> * Keep the current homepage, but make docs point to the gallery:
>   * homepage: https://webdev.dartlang.org/components (works no matter what the version is)

What do you mean about the versioning here? Is this link always to the stable version?

**Comment by nshahan** [comment]
Decided:
Homepage -> https://webdev.dartlang.org/components
Docs -> https://webdev.dartlang.org/api?package=angular_components
