### ISSUE TITLE
Tooltip cycles continuously when overlapping tooltip source

### ISSUE THREAD

**Issue by avilladsen** [dart-lang/angular_components#259]
If you can get a tooltip to overlap the tooltip source, the tooltip will continuously cycle between open and closed if you hold the mouse in the overlap.

I can get this to happen in the [examples gallery](https://dart-lang.github.io/angular_components_example/#/material_tooltip), which I believe is using angular_components 0.9.0-alpha+11. It happens in the tooltip source example, and the ink tooltip examples. The card and icon tooltip examples seem to be fine.

In the tooltip source example, the tooltip overlaps the source icon by default, so just hold the mouse over the icon.
In the ink tooltip examples, scroll so that the source element is right at the bottom of the window. That will get the tooltip to overlap the source element.

**Comment by TedSander** [comment]
Thanks for the report. I should have a fix in the next release.
