### ISSUE TITLE
Upgrade to protobuf 0.8.0

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular_components#267]
The current version constraint is `protobuf: ^0.7.1`. When a project depends on `angular_components: ^0.9.0-alpha`, the protobuf dependency forces use of `angular_components 0.9.0-alpha+7` (rather than the latest +12).

cc @kevmoo @kwalrath

**Comment by chalin** [comment]
A sample project for which this happens is https://github.com/angular-examples/lottery/blob/master/2-starteasy/pubspec.yaml.

**Comment by nshahan** [comment]
Bumped the dependency in v0.9.0-alpha+13.  #270
