### ISSUE TITLE
Error: Can't file stylesheet to import

### ISSUE THREAD

**Issue by afpatmin** [dart-lang/angular_components#271]
Serving my app (using pub run build_runner serve or webdev serve) results in a long list of errors in the build output;

`[SEVERE] angular_components|scss_builder on package:angular_components/scorecard/scoreboard.scss:

Error: Can't find stylesheet to import.
@import 'const/global',
        ^^^^^^^^^^^^^^
  /tmp/scratch_spaceYNRMBC/packages/angular_components/css/material/_material.scss 19:9  @import
  /tmp/scratch_spaceYNRMBC/packages/angular_components/scorecard/scoreboard.scss 5:9     root stylesheet`

The problem persists after I cleared my temp folder, running pub upgrade and pub cache repair, and the project doesn't have a custom build.yaml

My environment is 
OS: linux 64 bit
sdk: 2.0.0-dev.58.0
angular: 5.0.0-alpha+13
angular_components: 0.9.0-alpha+13
build_runner 0.8.9
build_web_compilers: 0.4.0+1
sass_builder 2.0.0

**Comment by nshahan** [comment]
For now the fix to unblock local development is to pin a dependency on dart_sass to a version pre v1.4.0: 

Add to your pubspec:
```yaml
dependency_overrides:
  sass: 1.3.2
```

There are a few issues opened that you can track for a permanent fix.
https://github.com/sass/dart-sass/issues/334
https://github.com/dart-lang/stagehand/issues/524

**Comment by nshahan** [comment]
This should be fixed in the latest versions of sass and sass_builder packages.
