### ISSUE TITLE
Problem with @import when using -I option

### ISSUE THREAD

**Issue by arpontes** [dart-lang/angular_components#276]
I've been watching other issues about this problem, and all of them is closed now, but the problem is not fixed yet.

I tested with the last release (version 1.6.2) and it isn't working. If I use version 1.3.2, all works fine.

I prepared a simple test for demonstration. The source code works with 1.3.2, and does not with 1.6.2. Just run the batch file "run.bat" (cmd must be in the path of run.bat, and run.bat assume sass is in the same folder).

[example.zip](https://github.com/dart-lang/angular_components/files/2119505/example.zip)

**Comment by zoechi** [comment]
Version 1.6.2 of what?
Are you sure you meant Angular components for Dart?

**Comment by arpontes** [comment]
Sorry, I don't know what gone wrong. I'm pretty sure I was in other project, but I think I was wrong! :-)
This issue was to be opened in dart-sass.
I'm closing it. Sorry.
