### ISSUE TITLE
MaterialToggleComponent doesn't provide ControlValueAccessor for forms

### ISSUE THREAD

**Issue by eredo** [dart-lang/angular_components#278]
The `MaterialToggleComponent` currently doesn't support `ngControl` directive, because there's no `ControlValueAccessor` implementation available. I guess it would be possible to adapt the `MaterialCheckboxComponent` implementation or provide a separate directive.

**Comment by TedSander** [comment]
Thanks for the bug. Let me see if I can implement this in the next couple of syncs.

**Comment by nshahan** [comment]
Published in v0.9.0-beta+1.
