### ISSUE TITLE
material-tree custom item renderer example uses deprecated, non-working code

### ISSUE THREAD

**Issue by montyr75** [dart-lang/angular_components#281]
I'm using a material-tree component with a custom renderer, and it's all constructed pretty much like the example in `dart-lang/angular_components_example` on GitHub, but two things are going badly. First, the function that returns my custom renderer has a return type of `ComponentRenderer`, which is apparently deprecated. Second, if I actually pass the custom renderer to the tree, I get: `EXCEPTION: Unsupported operation: You are using runApp or runAppAsync, which does not support loading a component with SlowComponentLoader. Please migrate this code to use ComponentLoader instead.` If I do not pass the renderer, the code runs.

Environment:
Windows 10
Dart 2.0.0-dev.66
angular: 5.0.0-alpha+15
angular_components: 0.9.0-alpha+15

**Comment by nshahan** [comment]
We just ran into this ourselves and have an updated demo coming soon in the next sync (hopefully today).

**Comment by nshahan** [comment]
The recent sync updated the Material Tree example to use component factories and is compatible with `runApp()`.

https://github.com/dart-lang/angular_components_example/blame/0af1b4a8326d5331b1c08ce30e82b976b7395e34/example/material_tree_example/lib/src/material_tree_nested_component_rendering_demo.dart
