### ISSUE TITLE
Problems generating API docs for v0.9.0-beta

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular_components#283]
Attempting to run the following command results in issues:

- **Error: Target of URI hasn't been generated**: 'package:angular_components/highlighted_text/highlighted_value.template.dart'. at lib/mixins/highlight_assistant_mixin.dart, line 7.
- **Warning: private API of package:angular_forms is reexported** by libraries in other packages

```console
> pub global run dartdoc --include=angular_components
...
analysis errors from source: package:angular_components/mixins/highlight_assistant_mixin.dart (/home/travis/build/dart-lang/site-webdev/tmp/pub-packages/angular_components-0.9.0-beta/lib/mixins/highlight_assistant_mixin.dart

[error] Target of URI hasn't been generated: 'package:angular_components/highlighted_text/highlighted_value.template.dart'. at lib/mixins/highlight_assistant_mixin.dart, line 7.

warning: private API of package:angular_forms is reexported by libraries in other packages: 
    from angular_components.NgModel: (file:///home/travis/.pub-cache/hosted/pub.dartlang.org/angular_forms-2.0.0-beta/lib/src/directives/ng_model.dart:58:7)
    referred to by angular_components: (file:///home/travis/build/dart-lang/site-webdev/tmp/pub-packages/angular_components-0.9.0-beta/lib/angular_components.dart:5:9)
...
```

cc @kwalrath

**Comment by chalin** [comment]
@nshahan, @TedSander - is this a known issue? Do you have any proposed workarounds?

**Comment by nshahan** [comment]
Running dartdocs isn't in our process internally so we are not tracking these types of failures.

Have you done this recently? Is this a new failure with the latest release? 
- It looks like material_input.dart has been exporting NgModel for some time.
- The docs were able to generate when the beta version was published.
https://pub.dartlang.org/documentation/angular_components/0.9.0-beta/

**Comment by chalin** [comment]
Have you done this recently? Is this a new failure with the latest release?

Yes, see [this Travis log](https://travis-ci.org/dart-lang/site-webdev/jobs/399243758).

Btw, dartdoc finishes "successfully" (exits with 0), but when I run a local link checker, I see these errors:

```nocode
http://localhost:4001/api/angular_components/angular_components/StepDirective
- (13:2) <link> => http://localhost:4001/api/static-assets/github.css (HTTP 404)
- (14:2) <link> => http://localhost:4001/api/static-assets/styles.css (HTTP 404)
- (31:8) 'angular_..' => http://localhost:4001/api/angular_components/angular_components-library.html (HTTP 301 => 404)
  - redirect path:
    - http://localhost:4001/api/angular_components/angular_components-library.html (301)
    - /api/angular_components/angular_components-library (404)
- (32:8) 'StepDire..' => http://localhost:4001/api/angular_components/StepDirective-class.html (HTTP 301 => 404)
  - redirect path:
    - http://localhost:4001/api/angular_components/StepDirective-class.html (301)
    - /api/angular_components/StepDirective-class (404)
...
```

Might `StepDirective` be exported in two ways?

**Comment by nshahan** [comment]
cc @alorenzen Any thoughts on exporting NgModel from material_input.dart here and the corresponding file internally?
https://github.com/dart-lang/angular_components/blob/d87231f2ff355fe28fdd77fc2a524ba87de66d2c/lib/material_input/material_input.dart#L19

**Comment by chalin** [comment]
> The docs were able to generate when the beta version was published

Do you know which command is used to generate the docs?

**Comment by chalin** [comment]
Ah, interesting: `StepDirective ` is the only folder that has an "index.html" file

```console
> cd ./publish/api/angular_components/angular_components/
> find . \( -name "index.html" \) -ls
  ... -rw-rw-r--    1 chalin  7471  2 Jul 16:50 StepDirective/index.html
```

The generated `<base href>` is invalid for that file. Hmm, I think that this happened before (and I needed to manually patch the API docs to fix it). I'll investigate a bit further and report here.

**Comment by nshahan** [comment]
> Do you know which command is used to generate the docs?

I don't know the command but it seems that dartdoc was updated to ignore the generated files error.
https://github.com/dart-lang/dartdoc/issues/1595

> Ah, interesting: StepDirective is the only folder that has an "index.html" file

Any idea what triggers that file to be created?

**Comment by chalin** [comment]
> Any idea what triggers that file to be created?

Ah, now I remember! The problem arises because `StepDirective` has a property named [index](https://pub.dartlang.org/documentation/angular_components/0.9.0-beta/material_stepper_material_step/StepDirective/), and the dartdoc generated API page for this member clashes with `index.html`.

You can reproduce the issue from the official API docs:
- Visit: https://pub.dartlang.org/documentation/angular_components/0.9.0-beta/material_stepper_material_step/StepDirective - notice the formatting is broken etc.
- Visit: https://pub.dartlang.org/documentation/angular_components/0.9.0-beta/material_stepper_material_step/StepDirective/index.html. This shows the `index` member page.

**Comment by nshahan** [comment]
I'm not sure I totally understand what the conflict is. I can see the StepDirective class here with proper  formatting but the page isn't named index.html.
https://pub.dartlang.org/documentation/angular_components/0.9.0-beta/material_stepper_material_step/StepDirective-class.html

If you understand could you file an issue with dartdoc? It seems like it should handle the case where there is a class member named index differently.

**Comment by chalin** [comment]
Done, see https://github.com/dart-lang/dartdoc/issues/1721
