### ISSUE TITLE
Slider is not mobile friendly

### ISSUE THREAD

**Issue by gazialankus** [dart-lang/angular_components#284]
On mobile browsers, one expects to be able to touch the slider's knob and drag it. However, the knob refuses to follow the finger. The only thing you can do is to tap the location where you want the knob to go to. It would be nice to be able to drag the knob with the finger. 

Given that this is the expected behavior on mobile, I'd say this is a bug. 

Steps to reproduce: open this link in a mobile browser and try dragging the slider knob without success: https://dart-lang.github.io/angular_components_example/#/material_slider

**Comment by TedSander** [comment]
I think I can get this for the next release. Pull request currently in progress.

**Comment by gazialankus** [comment]
Just wanted to say that I switched to github-sync branch and now sliders work as expected. :) Thank you.
