### ISSUE TITLE
Extending a MaterialComponent?

### ISSUE THREAD

**Issue by leocavalcante** [dart-lang/angular_components#286]
Is it possible to extend a `MaterialComponent`?

I tried the default assumption: `MyComponent extends MaterialExpansionPanel`, using my own `my_component.html` that was a 1:1 to [material_expansionpanel.html](https://github.com/dart-lang/angular_components/blob/master/lib/material_expansionpanel/material_expansionpanel.html) (that I would change a bit to have more elements on header), but is seams that directives was not extended, also it complains about `MaterialExpansionPanel` not having a empty constructor...

If it is possible, there is an example on how to extend a component?

**Comment by TedSander** [comment]
Yes it is possible, but it isn't considered best practice as it is pretty fragile if we make any changes to the component itself. Which is why we don't provide an example.

That said to do it you will need to copy the complete @Component or @Directive annotation and fill in all of those values. It is also better if it has a separate selector.

material-expansionpanel has a lot of areas to customize the elements in the header itself. There are three ng-content areas [name], [value], [action] which can take any additional elements. Can you use these to get the added elements in the header?

**Comment by leocavalcante** [comment]
I was trying to accomplish something like inbox.google.com, but that is ok, I'll avoid that. Thanks!

**Comment by TedSander** [comment]
Which part of inbox? I think you can do it. The actions can be the buttons on the right, and the name, and value can be conditional depending on if it is open or not.

Which part isn't working for you?

The actions will be shown or not based on the expand icon which might not be right for the inbox use case, but I think there might be a way around that if that is what is causing problems.

**Comment by leocavalcante** [comment]
Inbox header seams to be way more feature rich.
It has avatar which turns in checkboxes on mouse over, icons on the secondary text, buttons, images etc bellow second text. Its not just about the actions no the right.

![image](https://user-images.githubusercontent.com/183722/42355577-23d18b02-80a4-11e8-8d4b-aa22bfaaec2c.png)

**Comment by TedSander** [comment]
That all should be possible, but it will require some work on your part. The components that you pass into the [value] or [name] sections can be higher order components. You can do things such as:
_**Warning all white boarded code will not work as is**_
```html
<material-expansionpanel>
  <div name (mouseover)="icon = 'checkbox'" (mouseout)="icon = 'letter'">
    <material-icon [icon]="icon"></material-icon>
  </div>
  <div value> 
    <div>{{title}}</div>
    <div><material-icon icon="flag"></material-icon>{{flagMessage}}</div>
    <div><a href="issue">View Issue</a></div>
  </div>
</material-expansionpanel>```

We really believe in composition trying to come up with every possible combination of what someone could want to do. Thus we try to give areas for people to enhance the components through composition.

This is a generic expansion panel, not the implementation for inbox itself. But hopefully you can see how someone could enhance the generic component.

**Comment by TedSander** [comment]
Yep it is pretty flexible. The only restriction is you can't have a structural directive as the root of the content.

So this wouldn't work: `<div name *ngIf="show">...</div>`
but this does:
``` html
<div name>
  <div *ngIf="show">...</div>
</div>
```
