### ISSUE TITLE
App layout using MaterialListItemComponent throws exception

### ISSUE THREAD

**Issue by dougreese** [dart-lang/angular_components#288]
Using the [app_layout_example](https://github.com/dart-lang/angular_components_example/tree/master/example/app_layout_example/lib) code with `MaterialListItemComponent` included results in:

```
EXCEPTION: No provider found for DomService
```

Removing `MaterialListItemComponent` from the main app component directives list results in the error going away.  This could easily be something I have done wrong in my project, so I took the base Stagehand Angular app and added the app layout example to it.  

Full exception and stack trace in example:

https://github.com/dougreese/app_layout_example

**Comment by TedSander** [comment]
The list item needs DomService which is an injectable.

The easiest way to get it is to add the materialProviders to your root. You can see that here:
https://webdev.dartlang.org/codelabs/angular_components/2-starteasy#--set-up-the-root-components-dart-file

Thanks for using angular_components.
