### ISSUE TITLE
Discontinue use of "materialDirectives" list/helper

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular_components#289]
As hit by a user on Gitter, they accidentally had a variable named `step`, and it tried to use `StepDirective`, and failed because it was not a structural directive (https://github.com/dart-lang/angular/issues/1478). Based on internal discussions with @nshahan - this is never the right thing to use:

1. It forces the compiler to do a _lot_ of extra work figuring out which directives are used
2. It negatively effects tree-shaking, often we create extra (unused) directives and components
3. It can cause spectacular errors like above

At minimum, it should be `@Deprecated(...)`.

**Comment by TedSander** [comment]
So I had actually argued against using materialDirectives when angular_components first came out, and not having the single import entry point. DevRel/PMs overruled for ease of use. I'm fine changing it to not have the single entry points, but that is why we have them.

**Comment by matanlurey** [comment]
To be clear the single import is fine, it's the global list that causes real problems

**Comment by nshahan** [comment]
@chalin @kwalrath @kevmoo I'm onboard with at least marking it as deprecated with a message saying to use the individual directives and providers. Do you foresee many problems with that approach?

**Comment by chalin** [comment]
sgtm (no problems I can think of)

**Comment by kevmoo** [comment]
Mark as deprecated SGTM, @nshahan

**Comment by nshahan** [comment]
Deprecated in v0.9.0-beta+1.

**Comment by matanlurey** [comment]
Sg. We can close this, and you can delete whenever you feel like it @nshahan
