### ISSUE TITLE
custom tooltipShowDelay

### ISSUE THREAD

**Issue by lejard-h** [dart-lang/angular_components#291]
original issue: https://github.com/dart-lang/angular_components_example/issues/91

could we use a value provider to have a global configuration for tooltip delay ?

```dart
ValueProvider.forToken<int>(meterialTooltipDelayToken, 300)
```

**Comment by TedSander** [comment]
Talked with our UX and they really don't want to give users configuration around the tooltip delay. So we can't add a global configuration.

They did say they might change the value for future iterations which are coming soon, but they don't want to change it today. Sorry marking this as closed for now.

**Comment by kankaristo** [comment]
Any news on this? The default delay feels huge.

Material Design seems to recommend having a very small delay (e.g. most Google sites which should follow Material Design, as far as I know)?

**Comment by TedSander** [comment]
Same answer as before. The enterprise UX wanted these values, and they didn't want configuration. Until this changes we aren't adding configuration here sorry.
