### ISSUE TITLE
"During runtime this query will never find any elements"

### ISSUE THREAD

**Issue by jheyne** [dart-lang/angular_components#294]
- SDK version 2.0.0-dev.69.0
- analyzer 0.32.3
- angular 5.0.0-beta+1
- angular_components 0.9.0-beta

If I include MaterialTabPanelComponent as a directive, I see this analyzer error:

> Selector argument **Tab** for "@ContentChildren" is a Type, but it is not annotated with @Component or @Directive. During runtime this query will never find any elements. This may become an error in future versions of AngularDart

I see the error also referencing FocusableItem, FocusableActivateItem, and SelectionItem<T>. Originally I only saw the warning referencing Tab; after updating I see these as well.

**Comment by jheyne** [comment]
Note: During development testing the widgets seem to behave as expected.

**Comment by TedSander** [comment]
The warning is an angular bug. Should be fixed in the next release.

**Comment by nshahan** [comment]
These were cleaned up in Angular v5.0.0-beta+2. Downloading that version by running a pub upgrade should clear them up.
