### ISSUE TITLE
DatePicker works only for en-us locale

### ISSUE THREAD

**Issue by sestegra** [dart-lang/angular_components#295]
First day of week should be a parameter to support other locales.

**Comment by cpelling** [comment]
Hi Stéphane,

The first day of the week is set according to the current locale, as set by the intl package. See the intl package documentation for how to set the locale: https://pub.dartlang.org/packages/intl

Once this is done, the calendar should render with the appropriate first day of the week. For example, in en_GB it displays Monday as the first day.

Hope that helps.

Regards,
Chris

**Comment by sestegra** [comment]
@cpelling Thanks, it's so easy.
