### ISSUE TITLE
Bug in DomTreeIterator.moveNext

### ISSUE THREAD

**Issue by jolleekin** [dart-lang/angular_components#299]
Seems like there's a bug in [DomTreeIterator.moveNext](https://github.com/dart-lang/angular_components/blob/master/lib/utils/browser/dom_iterator/dom_iterator.dart#L68)
``` dart
    if (_element == _scope && _element.children.isEmpty) {
      _element == null; // should be an assignment
      return false;
    }
```

**Comment by TedSander** [comment]
Sorry I don't see the bug. I believe this is how the interaction of the utility was made. If their are no more elements to move to moveNext will set the _element to be null, and return false. The other feature is that the _scope element limits where the element will move to.

Can you elaborate more on why you believe this is a bug, and in what use cases?

**Comment by jolleekin** [comment]
It should be `_element = null` (assignment) rather than `_element == null` (comparison).

**Comment by TedSander** [comment]
Thanks read that line three times and missed it. I'll have a fix for the next release.
