### ISSUE TITLE
Unable to use *ngFor in material-stepper

### ISSUE THREAD

**Issue by sandrija** [dart-lang/angular_components#309]
Hi all, I am new in dart.

When i try to use ngFor inside material-stepper for adding steps from some List i got error

Invalid decorator in 'template' element
                    <template *ngFor="let formStep of formSteps"

Code is working fine outside material-stepper when printing in div elements, but not inside material-stepper. Is there a solution for this?

```
 <template *ngFor="let formStep of formSteps"
                              step
                              name="test">
                        <h1>{{formStep.title}} - content</h1>
                    </template>

```

**Comment by zoechi** [comment]
`*ngFor` can't be used with `<template>`, you would need `<template ngFor let-formStep [ngForOf]="formSteps" ...`

If you instead use `<ng-container>` you can use 

```html
 <ng-container *ngFor="let formStep of formSteps"
                              step
                              name="test">
                        <h1>{{formStep.title}} - content</h1>
                    </ng-container>
```

**Comment by sandrija** [comment]
Thx for quick reply, can you explain more
<template ngFor let-formStep [ngForOf]="formSteps" ...
I can see that this will work, but it only displays first step

**Comment by zoechi** [comment]
I haven't used this component. Perhaps you need to change `name="test"` so that it is not the same for each step.
I'd suggest to use `<ng-container>` because this way you can stick to the more common syntax.

**Comment by TedSander** [comment]
Both step and ngFor are what we call structural directives. That means they both modify the DOM structure. As such when you try to use multiple on a single entity the order of operations is not clear. 

In this case you need to separate the ngFor and the step.

```html
<ng-container *ngFor="let formStep of formSteps">
  <template step name="test">
    <h1>{{formStep.title}} - content</h1>
  </template>
</ng-container>
```
