### ISSUE TITLE
Make _updateChildComponent from DynamicComponent public

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular_components#317]
Hi,

I would like to be able to create a component that extends **DynamicComponent** and override the **_updateChildComponent** to set some properties outside **RendersValue**'s scope.
I guess that changing that function to public is not drastic and would help a lot.

**Comment by TedSander** [comment]
Why not use the onLoad stream for this?

**Comment by jodinathan** [comment]
didn't see it! 

thanks =]
