### ISSUE TITLE
MaterialExpansionPanel does not work when nested

### ISSUE THREAD

**Issue by fabitamas** [dart-lang/angular_components#318]
When I try to open a nested expansion panel, the top one closes and I end up with everything closed. This used to work in version 0.8.0, but now I'm trying to use Dart 2 and forced to bump up to 0.9.0.

I'm using the following structure:

```
<material-expansionpanel-set>
    <material-expansionpanel name="A">
      <material-expansionpanel-set>
        <material-expansionpanel name="X"></material-expansionpanel>
        <material-expansionpanel name="Y"></material-expansionpanel>
        <material-expansionpanel name="Z"></material-expansionpanel>
      </material-expansionpanel-set>
   </material-expansionpanel>
   <material-expansionpanel name="B">
 </material-expansionpanel-set>
```

So when I click on A, it opens as expected. After that I click on X, Y or Z, it opens, but A closes, so I cannot see anything inside X, Y or Z. When I open A back, it causes X, Y or Z to close, so I still cannot get to see the contents of X, Y or Z

**Comment by nshahan** [comment]
@phantomesse

**Comment by phantomesse** [comment]
Hi Tamas! Thanks for catching this bug. I'm working on a fix.
