### ISSUE TITLE
Animation Frame Fired too often from dialog

### ISSUE THREAD

**Issue by sclee15** [dart-lang/angular_components#322]
Today, I got a performance issue that related with Animation Frame Fired related.

I tried to trackdown with the chrome performance tool and I found that material-dialog was the cause.

after i removed the components, the problem is resolved.

So far i am trying to replace the material-dialog but i think it would be good to submit an issue.

thank you.

**Comment by nshahan** [comment]
Can you share a minimal reproduction?

**Comment by TedSander** [comment]
This is on purpose. We find using the animationFrame to have the popup in the correct position worked better than other strategies. That said you can turn off this strategy itself if you don't like that behavior. To do that use this injection value:

`provide(overlayRepositionLoop, useValue: false),`
