### ISSUE TITLE
acx-scoreboard not working in iPhone

### ISSUE THREAD

**Issue by mylaimani** [dart-lang/angular_components#328]
I created a component like this. It is working fine in Android and normal computer web browsers. But it is not working in iPhone (Chevron_left and chevron_right button is not showing)

<acx-scoreboard isScrollable="true" scrollable *ngIf="liveScores.length > 0">
        <acx-scorecard
                *ngFor="let liveScore of liveScores">
            <carouselFixture [stream]="liveScore.stream" *ngIf="liveScore.viewModelType == 'OutdoorCricketSummary'" ></carouselFixture>
        </acx-scorecard>
    </acx-scoreboard>

**Comment by TedSander** [comment]
Working fine for me on an iPad. How are you loading the icon font?

![img_5322](https://user-images.githubusercontent.com/5643740/45179761-42638d80-b1ce-11e8-89ac-964aee82030d.png)

**Comment by TedSander** [comment]
Can you provide a screenshot? Can you try it using the gallery.

I'm worried we aren't talking about the same thing.

**Comment by mylaimani** [comment]
Here I am sending you the video, actually in gallery also it is not working  [https://dart-lang.github.io/angular_components_example/#scorecard]
)
[2018-09-07_09-30-43.zip](https://github.com/dart-lang/angular_components/files/2359445/2018-09-07_09-30-43.zip)

[2018-09-07_09-25-50.zip](https://github.com/dart-lang/angular_components/files/2359433/2018-09-07_09-25-50.zip)

I feel touch and move function will solve this problem... can you tell me how to do it

**Comment by mylaimani** [comment]
One thing I am sure, this component is having problem when the screen size is small.

Touch and move functionality is needed for this component (for mobile friendly usages)….

**Comment by nshahan** [comment]
So it sounds like if the content area becomes small enough that only a single card can be displayed at a time, the arrows stop working.

**Comment by TedSander** [comment]
Added an issue to better capture the bug you are seeing.
