### ISSUE TITLE
Bump protobuf dependency to ^0.10.0

### ISSUE THREAD

**Issue by jhfbosman** [dart-lang/angular_components#332]
Could you plase bump the protobuf dependency from ^0.9.0 to ^0.10.0? I can't make use of the newest dart-protoc plugin, nor use ^0.10.0 in a package as the generated dart code is incompatible with ^0.9.0.

I get errors like the following when using 0.9.0 and the latest protoc plugin: 

"The named parameter 'package' isn't defined."
"The name 'PackageName' isn't a class."
"The method 'copyWith' isn't defined in a superclass of 'GeneratedMessage'."
"The method 'freeze' isn't defined for the class '<my-proto-message>'."

**Comment by nshahan** [comment]
Yeah, I've been working on a new workflow to produce the generated proto files. I will update the dependency once those changes are merged.

**Comment by nshahan** [comment]
Fixed in 3dd4207.

**Comment by jhfbosman** [comment]
Thanks...

Just on a side-note: could tell me how you managed to add the *library* directive in the generated .pb.dart files  for *date.proto*? I can't seem to find any reference as to how this is done...

**Comment by nshahan** [comment]
The library directives in the generated output were an artifact of the old version of the protoc_plugin that was used to generate those files. It has been removed in later versions.
https://github.com/dart-lang/dart-protoc-plugin/pull/107/files

The latest versions I generated don't have them anymore.
