### ISSUE TITLE
MaterialDropdown Multiple Select doesn't handle mixture of key and mouse actions

### ISSUE THREAD

**Issue by ijd-github** [dart-lang/angular_components#338]
When using a dropdown multi-select if you switch from selecting with the mouse to selecting with the keyboard (arrow up, arrow down and spacebar) the selection doesn't work and triggers add/delete events on the last mouse selection. This also occurs on the AngularDart Gallery example for MultiSelect Dropdown.

**Comment by baitarakhov** [comment]
+1
Example in tutorial AngularDart:
https://webdev.dartlang.org/examples/toh-6/#dashboard

**Comment by nshahan** [comment]
Thanks, a fix has landed internally and should be include in our next sync.

**Comment by nshahan** [comment]
The issue appears to be resolved in v0.11.0. Feel free to reopen if you can still reproduce it.
