### ISSUE TITLE
material_dialog mixin: material-dialog-header-color()

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular_components#341]
```
Error: Top-level selectors may not contain the parent selector "&".
  ::ng-deep .wrapper > header,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  package:angular_components/material_dialog/_mixins.scss 9:3  material-dialog-header-color()
  - 354:1                   
```

I'm getting the above error trying to use this mixin.

**Comment by nshahan** [comment]
Admittedly, the Sass mixins have been developed over some years and we have changed how they should be written so they are not all totally consistent with each other. It's something that we have recognized and are working to cleanup in the future.

That particular mixin needs to be wrapped in some kind of target like in the example here:
https://github.com/dart-lang/angular_components/blob/81e93c87a6aefb8c5377c00bdab2632d0a2e322d/examples/material_dialog_example/lib/material_dialog_example.scss#L57-L66
