### ISSUE TITLE
material-toggle css changes when label is from a getter

### ISSUE THREAD

**Issue by serverplumber** [dart-lang/angular_components#346]
This works fine, it looks good.
```
<material-drawer temporary #drawer="drawer" overlay>
  <material-list *deferredContent>
    <div group class="mat-drawer-spacer"></div>
    <div group>
      <material-list-item>
        <material-icon icon="star"></material-icon>about
      </material-list-item>
    </div>
    <div group class="lang-toggle">
      <material-toggle [(checked)]="anglais"
        label="blabla"> 
      </material-toggle>
    </div>
  </material-list>
</material-drawer>
```
It looks like this : 
![screen shot 2018-10-22 at 6 53 39 pm](https://user-images.githubusercontent.com/7907191/47323968-fd83a100-d62b-11e8-950c-c49b728c7830.png)
When I add the following in drawer_component.dart :
`String toto = 'blabla';`

then change 

`label="{{ blabla }}">`

the format hits the fan and I lose a bunch of css classes in the toggle component.
![screen shot 2018-10-22 at 7 02 50 pm](https://user-images.githubusercontent.com/7907191/47324275-222c4880-d62d-11e8-8dca-04bff7dcdf4d.png)

Is this on me? I need to use getters to use Intl.

**Comment by TedSander** [comment]
What happens when you use the pattern [label]="toto"?

**Comment by serverplumber** [comment]
Same difference.

**Comment by TedSander** [comment]
What CSS are you using for lang-toggle? or what does your styling look like?

**Comment by serverplumber** [comment]
I use some simple sass. I call a mixin and a bit of cruft to make the "off" toggle bar coloured since it's an either or representation, not a true/false one.
```
.lang-toggle {
    @include material-toggle-theme(
      $primary-color: $mat-light-green-500,
      $off-btn-color: $mat-pink-500);

      ::ng-deep material-toggle.themeable .tgl-bar {
        background-color: rgba($mat-pink-500, .12);
      }
  }
```

Makes no difference when I remove it. (I pick colours I can see ;)

**Comment by TedSander** [comment]
Ahh found the problem. The label is being dual used in this case it is both a CSS selector and the input. You can see it here: https://github.com/dart-lang/angular_components/blob/41f948264e9f9b40700b237214f9d14f4998a358/angular_components/lib/material_list/material_list.scss#L97

[label] is only going to match label="blah" and not [label]="blah" or label="{blah}" the last two don't actually get reflected in the DOM.

The easiest workaround is to do:
```
<material-toggle [(checked)]="customWidth" label [label]="toto"></material-toggle>
```

This also works:
```
<material-toggle [(checked)]="customWidth" [label]="toto" [attr.label.if]="true">
</material-toggle>
```

Or you could apply the CSS for the label list item yourself.
