### ISSUE TITLE
Running angular_components with Dart SDK 2.1.0-dev

### ISSUE THREAD

**Issue by JCzz** [dart-lang/angular_components#347]
I have installed the latest Dart SDK 2.1.0-dev.7.1 to try out Material design examples. But I am unable to run the examples - like angular_components/examples/material_card_example

I have git cloned the repo and when running webdev serve in one of the samples I get:

```
webdev could not run for this project.
You must have a dependency on `build_runner` in `pubspec.yaml`.
# pubspec.yaml
dev_dependencies:
  build_runner: >=0.8.10 <2.0.0
You must have a dependency on `build_web_compilers` in `pubspec.yaml`.
# pubspec.yaml
dev_dependencies:
  build_web_compilers: >=0.3.6 <0.5.0

```

Do you know how to run the samples?

**Comment by zoechi** [comment]
See also the related discussion on https://stackoverflow.com/questions/52949287/running-angular-components-with-dart-sdk-2-1-0-dev

**Comment by nshahan** [comment]
All of the individual examples haven't been configured to work with the external build system.

Try running `webdev serve web` from the angular_components_example subdirectory:
https://github.com/dart-lang/angular_components/tree/master/examples/angular_components_example

Then navigate to the Material Card section to see the example.
