### ISSUE TITLE
No IE support!?

### ISSUE THREAD

**Issue by uloga** [dart-lang/angular_components#349]
Note: The angular_components package does not support Internet Explorer.

So there is no IE support at all!? No polyfills, nothing!? Whats the point of using this framework!?
Most governmental and major other sectors are not allowed to use other browsers than IE.

**Comment by TedSander** [comment]
Yes it does not support IE, but it does support Edge, Firefox, Safari, Chrome and others.

I'm sorry it doesn't work for your use case, but our requirements allowed it, and it was very helpful to not have to support 5 year old technology and allows us to have better maintenance, less faster code, and less bugs.

If IE is a requirement sorry, but this package will not work for you.

**Comment by uloga** [comment]
Too bad,  as a consultant at large governmental, insurance, energy, banking organisations I was looking forward introducing Dart as one language for everything. IMO Flutter was the gateway for google to get more organisations / companies to use Dart, but with this type of decision making by Dart team it's impossible that Dart is ever gonna replace Javascript. 90% of large organisation with thousands of developers are using angular typescript, even flutter may suffer because of this type of decision not to support "5 year old technology" since nativescript is now supporting typescript. Next week I'm going to consult at a large Bank here in EU and when they ask me about pwa's, ie support and not to mention kaiOS which is second most used mobile OS after android and covers 10+ mill of their customers, I'm not gonna be able to say that Dart is a great option. :( Not sure who's making decisions on Dart but IMHO I'd fire anyone who does not see the opportunity and wastes resources.

**Comment by TedSander** [comment]
Dart2js does support IE11, along with Angular. It is just this widget set that does not. Thank you for your passion and desire to use the widgets.
