### ISSUE TITLE
Multiple date/month picker lose focus

### ISSUE THREAD

**Issue by lejard-h** [dart-lang/angular_components#358]
On version `0.10.0`
I have multiple month picker open at the same time with selected month on each.

When I select a month on the first picker, the second look like it lost the selected month, the blue background disapear, but when I pass the mouse over it, the background color come back, very disturbing for the user.

I am using min/maxDate on it, and from what I see it call `_resetView();` which is not adding back `boundary` classes on selectedDate.

**Comment by nshahan** [comment]
There were multiple updates to the focus handling for the drop downs and overlays in the latest release, v0.11.0. Are you able to reproduce this issue after updating to latest?

**Comment by lejard-h** [comment]
I still have the issue. I also use maxDate and minDate input

code to reproduce

```dart
static Date date(int months) => Date.today().add(months: months);

CalendarState start = CalendarState.selected(
  [CalendarSelection('default', date(-5), date(-5))],
  resolution: CalendarResolution.months,
);

CalendarState end = CalendarState.selected(
  [CalendarSelection('default', date(5), date(5))],
  resolution: CalendarResolution.months,
);

Date get startMaxDate => end.selection(end.currentSelection).end;

Date get endMinDate => start.selection(start.currentSelection).start;
```

```html
<material-month-picker mode="single-date" [maxDate]="startMaxDate" [(state)]="start"></material-month-picker>
<material-month-picker mode="single-date" [minDate]="endMinDate" [(state)]="end"></material-month-picker>
```

**Comment by cpelling** [comment]
Thanks for your patience over the Christmas break, and for the simple repro case. I've identified the issue and am preparing a fix.
