### ISSUE TITLE
itemRenderer type mismatch

### ISSUE THREAD

**Issue by grundid** [dart-lang/angular_components#364]
After updating to version 0.11.0 I see a runtime exception when assigning an itemRenderer.

`Type '(Location) => String' is not a subtype of expected type '(dynamic) => String'.`

When I change the parameter of my itemRenderer to "Object" it is working however I would expect that with the latest version the itemRenderer should better understand types.

**Comment by eredo** [comment]
With angular 5.1 typed components where introduced, therefore you'll need to define the generic type of your component, so itemRenderer is no longer `(dynamic) => String`. For example if you're using the `material-dropdown-select` component within a component called: "MyComponent" the definition should look like:

```dart
@Component(
  selector: 'my-component',
  //...
  directives: [MaterialDropdownComponent],
  directiveTypes: [Typed<MaterialDropdownComponent<String>>()],
)
class MyComponent {}
```

See https://pub.dartlang.org/documentation/angular/latest/angular/Typed-class.html for further information.

**Comment by grundid** [comment]
Thank you. This solves the problem. At the same time this looks like a huge overhead if I have a form with 10 select lists and 10 different types...

I'm following the change log of AngularDart (https://webdev.dartlang.org/changelog) and the above info is missing there.

**Comment by nshahan** [comment]
@grundid FYI the changelog you linked was for the AngularDart website, not the AngularDart package. The changes you are interested in are here: https://pub.dartlang.org/packages/angular#-changelog-tab-

The details for the new generic component features are there. It is linked from the page you mentioned.
