### ISSUE TITLE
Request for a MRE materials-dropdown-select example

### ISSUE THREAD

**Issue by 1beb** [dart-lang/angular_components#366]
The current example has a lot going on, so much, that it's challenging for someone new to make sense of what parts are relevant to a minimum reproducible example.

**Comment by nshahan** [comment]
The dropdown select example page now has two demos, the simple and full version. See the simple demo files here:
https://github.com/dart-lang/angular_components/blob/c6cb3d783e72ff1ed7974f18b7f169778c73d39b/examples/material_select_example/lib/material_dropdown_select_simple_demo.dart

https://github.com/dart-lang/angular_components/blob/c6cb3d783e72ff1ed7974f18b7f169778c73d39b/examples/material_select_example/lib/material_dropdown_select_simple_demo.html
