### ISSUE TITLE
Material icon does not handle custom svg images

### ISSUE THREAD

**Issue by szepeshazi** [dart-lang/angular_components#384]
Leaving the `icon` attribute empty and providing a custom svg background image for `material-icon` renders an empty icon (svg content is not displayed).

icon_example.dart
```
@Component(
    selector: 'icon-example',
    template: '''
    <div>
      A custom svg icon:
      <material-icon class="breakfast"></material-icon>
    </div>
    ''',
    styleUrls : ["icon_example.css"],
    directives: [MaterialIconComponent])
class IconExampleComponent {}
```

icon_example.scss
```
@import 'package:angular_components/css/material/material';
@import 'package:angular_components/material_icon/mixins';

:host {
  .breakfast {
    @include svg-icon(url("/img/breakfast.svg"));
  }
}
```

The custom SVG icon also does not show up in the official example gallery: 
https://dart-lang.github.io/angular_components/#/material_icon

**Comment by nshahan** [comment]
Thanks for pointing this out. I just verified that it does work, but our example is currently broken. I'll submit a fix to get it working.

On your example, check your network tab in the dev tools. It depends on how your are serving your app but I'm guessing you will find a failed download for the .svg file. Working out the correct path is tricky. For example if you are serving with `webdev` our `build_runner` you can fix the path with something like `url("packages/YOUR PACKAGE NAME/img/breakfast.svg")`.

**Comment by nshahan** [comment]
Ah great. Glad to hear it's working for you now. We have a pending fix to properly size the icon that should be landing in the next version: https://github.com/dart-lang/angular_components/pull/378/commits/5f2d9d20d2dbfd6f4c11f7ca22e9c0ae500518c3.
