### ISSUE TITLE
NoSuchMethodError: The getter 'scheme' was called on null.

### ISSUE THREAD

**Issue by vintzl** [dart-lang/angular_components#388]
angular: ^5.2.0
dart 2.1.0-1

if `build_runner`  > `1.2.3` I get

	[SEVERE] angular on package:angular_components/mixins/highlight_assistant_mixin.dart:
	Unhandled exception in the AngularDart compiler!

	Please report a bug: https://github.com/dart-lang/angular/issues/new
	NoSuchMethodError: The getter 'scheme' was called on null.
	Receiver: null
	Tried calling: scheme
	[SEVERE] build_web_compilers|entrypoint on web/main.dart:
	Unable to find modules for some sources, this is usually the result of either a
	bad import, a missing dependency in a package (or possibly a dev_dependency
	needs to move to a real dependency), or a build failure (if importing a
	generated file).

	Please check the following imports:

	`import 'mixins/highlight_assistant_mixin.template.dart' as _ref186;` from angular_components|lib/angular_components.template.dart at 193:1
	`import 'package:angular_components/mixins/highlight_assistant_mixin.template.dart' as _ref19;` from angular_components|lib/material_input/material_auto_suggest_input.template.dart at 27:1

**Comment by vintzl** [comment]
Here what I did:
writing in `pubspec.yaml`

```
# override for intl_translation: ^0.17.2
dependency_overrides:
  analyzer: ^0.34.0
build_runner: ^1.2.0
```
did a `pub upgrade` and `pub` leads to this:
`> build_runner 1.2.5 (was 1.2.3)`

For now I stick to this:
`build_runner:  1.2.3`

**Comment by nshahan** [comment]
OK, the dependency override on the analyzer package explains how the version solve pulled in incompatible versions.

I'm going to close this issue for now and you can track an issue in the build package for a fix regarding the original error you posted. 
https://github.com/dart-lang/build/issues/2022

**Comment by afpatmin** [comment]
I posted dart-lang/build#2022, and I also used dependency override on analyzer. 

Anyone using angular ^5.2.0 alongside intl_translation would run into the same problem.

There is an open issue about it here: dart-lang/i18n#510

**Comment by nshahan** [comment]
If you are already overriding the analyzer package, try it with build_resolver v1.0.2.
https://pub.dartlang.org/packages/build_resolvers/versions/1.0.2

It includes an update that should hopefully fix this issue.

**Comment by afpatmin** [comment]
Yep thanks that fixed it on my end

**Comment by kendji** [comment]
I resolved that with "flutter clean'.
