### ISSUE TITLE
material-auto-suggest-input preventing page from loading

### ISSUE THREAD

**Issue by DanielSmith1239** [dart-lang/angular_components#395]
Hello,
I'm trying to show material-auto-suggest-input in my template, however when I add it, it prevents the page from loading. Here is my template:
<img width="439" alt="screen shot 2019-02-24 at 3 00 19 pm" src="https://user-images.githubusercontent.com/11168127/53304572-ee646800-3844-11e9-8551-5816069d40ec.png">

Here is my dart code:
<img width="639" alt="screen shot 2019-02-24 at 3 01 12 pm" src="https://user-images.githubusercontent.com/11168127/53304585-0c31cd00-3845-11e9-9e2e-f60fe1588e7f.png">

When I remove the material-auto-suggest-input tag, the page loads fine. Any tips?

**Comment by DanielSmith1239** [comment]
Just to clarify, no errors are printed to the console. The page simply doesn't load.

**Comment by nshahan** [comment]
That code looks very similar to the example that we know is working. When you say "the page simply doesn't load" do you mean 404 error or it loads but just looks blank? If blank, what appears in the dom? Is your angular app being loaded at all? Does your app load when it includes a smaller component like material button?

**Comment by giorgiofran** [comment]
I guess your are missing the providers definition:
`    providers: [materialProviders],`

**Comment by DanielSmith1239** [comment]
@giorgiofran `materialProviders` is deprecated I believe.
@nshahan Exactly, It's copied and pasted from the example. That's why I'm so confused. I mean that the other angular components on the page don't load. I have something like `<my-app>Loading...</my-app>` in my `index.html`, and adding the `material-auto-suggest-input` makes it so the page only displays "Loading..." and never loads the components.

**Comment by giorgiofran** [comment]
- `materialDirectives` is deprecated, not `materialProviders`
- As providers are inherited from the calling component, normally `materialProviders` is set in the top component (if you use a default project, the `AppComponent)` so that all components of the project will not need to define it again.
- I created a new project (Dart 2.0) with your example and it worked adding `materialProviders` in `SearchBoxComponent` or in `AppComponent`

**Comment by DanielSmith1239** [comment]
Adding `materialProviders` fixed the issue, thanks.
