### ISSUE TITLE
angular_components.dart needs to export has_factory.dart

### ISSUE THREAD

**Issue by tonosama-atlacatl** [dart-lang/angular_components#401]
I've been tasked with the glorious privilege of migrating our dart project to sdk 2.2.+,
It seems _ComponentRenderer_ is now deprecated, and instead I need to use FactoryRenderer..
Ok...but, angular_components.dart does NOT export **/lib/model/ui/has_factory.dart**
Can we add an export for **has_factory.dart**?

**Comment by TedSander** [comment]
@nshahan to comment as he would know better.

To my knoweldge we have been moving away from the uber export. Feel free to depend on the file directly it isn't in a src folder.

`@import 'package:angular_components/model/ui/has_factory.dart';`

**Comment by nshahan** [comment]
We deprecated the `materialDirectives` and `materialProviders` lists in that file and at that time I stopped updating the exports as well. See #289.

It just made more sense to just import the files you need to use as @TedSander mentioned.
