### ISSUE TITLE
optional autoDismiss for MaterialAutoSuggestInputComponent

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular_components#402]
I would like force a user selection on ```MaterialAutoSuggestInputComponent``` but for that I need the autoDismiss as an ```Input()``` to work correctly.

Right now I am setting it as ```box.autoDismiss = false;``` where ```box``` comes from a ```ViewChild``` binding.
After the popup is dismissed one time, it stays fixed.

Can you add the meta ```@Input()``` to the ```autoDismiss``` property of ```MaterialAutoSuggestInputComponent``` ?

**Comment by TedSander** [comment]
Sorry we don't want to make autoDismiss configurable for this component. It complicates the component and creates a lot more edge cases than we would like.

Thanks for the suggestion.
