### ISSUE TITLE
Pressing escape after material dialog is opened causes buttons to get disabled forever

### ISSUE THREAD

**Issue by drbcode** [dart-lang/angular_components#403]
If you go to [angular dart component gallery](https://dart-lang.github.io/angular_components/#/material_dialog)

and open some dialogs and press escape, then button to open the dialog will be disabled forever until you refresh the page. It happens only for some dialogs and not for all dialogs. 

It happens on linux and mac OS.

For example, if you open the dialog and after that you opened find tool by pressing `Ctrl + F`, after pressing escape both find tool and material-dialog are closed, but the buttons to re-open material-dialog are permanently disabled until the page is reloaded.

**Comment by drbcode** [comment]
I noticed that in some examples, buttons are left enabled after pressing escape, but clicking on the enabled buttons doesn't open the dialog.

**Comment by TedSander** [comment]
So this is just a problem with the gallery not using `[(visible)]` syntax for the dialog examples. It is actually already fixed internally, but we haven't pushed those changes to github yet.

cc: @nshahan can you close when we do our next push?

**Comment by nshahan** [comment]
Fixed in the latest publish of the gallery.
