### ISSUE TITLE
dropdown animation doesn't consider size from PopupSizeProvider

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_components#41]
![2](https://cloud.githubusercontent.com/assets/405837/21433424/0d52622c-c870-11e6-9211-baafd4c0d646.gif)

During the animation the full size of the content is used and only afterwards the size from the provider is applied. 
This makes the vertical window scrollbar appear during the animation.

**Comment by TedSander** [comment]
Created an internal tracking bug. I don't think we have one for this currently.

**Comment by nshahan** [comment]
I think this is fixed. Please reopen if you still see the issue.
