### ISSUE TITLE
RTL support for tab indicator

### ISSUE THREAD

**Issue by hamidrezabstn** [dart-lang/angular_components#418]
https://github.com/dart-lang/angular_components/blob/3f79425a42119ecf4c63ea0468f0179ba32767c4/angular_components/lib/material_tab/fixed_material_tab_strip.scss#L34

above line causes inappropriate behavior in rtl sites because it bounds to 'left'!!! 
some how it should be 'right center' when the site is rtl

**Comment by TedSander** [comment]
You need to use CSS Janus to flip the style sheet. That is how we do RTL. So this will get flipped by that.

https://github.com/cssjanus/cssjanus

**Comment by hamidrezabstn** [comment]
hi 
thanks to your replay ! 
you mean i should use a tool to flip css to rtlt ? is that really a fix ??? 
of course i can flip this line even by hand but it needs to disable encapsulation for my component and then that will cause conflicts with other component's css files! 
any suggestion other than fliping by hand or tools ???
is there another workaround using dart or css mixins ?

**Comment by nshahan** [comment]
Yes, there is a need to apply another tool to handle RTL changes. It is another example of a design choice made by this package. Anything that can be handled simply by CSS usually is because that will provide the best performance.

**Comment by hamidrezabstn** [comment]
> Yes, there is a need to apply another tool to handle RTL changes. It is another example of a design choice made by this package. Anything that can be handled simply by CSS usually is because that will provide the best performance.

hi @nshahan 
how about encapsulation thing that i've saied ?

**Comment by TedSander** [comment]
What happens is two AngularDart apps are served. One with the CSS processed with CSSJanus during the compile, and another with it not. Encapsulation doesn't come into play at all as the transformation happens before.

**Comment by hamidrezabstn** [comment]
> What happens is two AngularDart apps are served. One with the CSS processed with CSSJanus during the compile, and another with it not. Encapsulation doesn't come into play at all as the transformation happens before.

can u please provide me a link to a tutorial about adding cssjanus or any other js tools to my angulardart build process ?

**Comment by TedSander** [comment]
Sorry but our build system is completely different inside than it is externally, and as such it is going to be an exercise for the user. I would imagine you would need a builder for it and add it to your build.yaml as a step that runs before scss_builder

**Comment by hamidrezabstn** [comment]
@TedSander 
thank u so much i will give it a shot!
