### ISSUE TITLE
Support for latest build_config

### ISSUE THREAD

**Issue by Eddydpyl** [dart-lang/angular_components#421]
See https://github.com/dart-lang/webdev/issues/408

**Comment by delizondo** [comment]
same here!

**Comment by nshahan** [comment]
Looks good. I'm working on a sync of the latest changes and I will include this as well.

**Comment by nshahan** [comment]
I've published a new version that works with the latest angular and webdev packages.

**Comment by Eddydpyl** [comment]
@nshahan would it be possible for you to add these changes to the previous version? The newest one requires angular 6.0.0 and there are still many packages that haven't upgraded their dependencies to this new version of angular, which is still in alpha.

**Comment by nshahan** [comment]
@Eddydpyl I published version v0.13.0+1 that will build with the latest version of webdev.

**Comment by Eddydpyl** [comment]
Awesome, thanks!
