### ISSUE TITLE
MaterialButtonComponent did not have pending input?

### ISSUE THREAD

**Issue by oonid** [dart-lang/angular_components#429]
I saw that `MaterialYesNoButtonsComponent` has `pending` input, but `MaterialButtonComponent` did not have it.

Is there any plan to add `pending` input to `MaterialButtonComponent`?

thank you.

**Comment by TedSander** [comment]
No plan to add that to button. Yes/No handles more complicated use cases and we wouldn't want to bloat button with a spinner to give this functionality.
