### ISSUE TITLE
Can not dynamically change type of MaterialInput

### ISSUE THREAD

**Issue by Ninjadeer** [dart-lang/angular_components#430]
register_component.dart

```
import 'package:angular/angular.dart';
import 'package:angular_components/angular_components.dart';

@Component(
  selector: 'app-register',
  templateUrl: 'register_component.html',
  styleUrls: [
  ],
  directives: [
    CORE_DIRECTIVES,
    MaterialInputComponent,
    MaterialButtonComponent,
    MaterialIconComponent
  ]
)

class LoginComponent {
  bool passwordVisible = false;
}
```

register_component.html
```
<material-input
        [type]="passwordVisible ? 'text' : 'password'"
></material-input>

<input [type]="passwordVisible ? 'text' : 'password'"/>

<material-button
        icon
        (click)="passwordVisible = !passwordVisible">
    <material-icon
            [icon]="passwordVisible ? 'visibility' : 'visibility_off'"
    ></material-icon>
</material-button>
```

Expected the input type to toggle between "password" and "text"

Tried with version "0.14.0-alpha+1" 
Compiled with dart2js

Apologies if I have missed something trivial.

**Comment by TedSander** [comment]
https://github.com/dart-lang/angular_components/issues/210

We do this on purpose, but there is a workaround.

**Comment by Ninjadeer** [comment]
Hi Ted, thanks for your reply.

I was trying a few work arounds, such as hooking into the changeDetector, perhaps extending the input.

If you have a workaround that's prefered could you signpost to the documentation if it exists or share it on this issue for others?

**Comment by TedSander** [comment]
ChangeDetectors hooked into a directive is the ‘same’ context as the
component it is on. So calling markForChecked when you switch the type from
the directive should work.

**Comment by Ninjadeer** [comment]
Cheers!

Missed the "#210" reference in the message, thought it was referencing the issue.

Thanks for your time :)
