### ISSUE TITLE
material-input multiline should have a different appearance than single line

### ISSUE THREAD

**Issue by e-belair** [dart-lang/angular_components#435]
Users cannot make the difference between single line and multiline.

On the [Angular input example](https://material.angular.io/components/input/overview) (leave a comment), if the input is multiline, there is a corner icon at bottom right, so user can resize the textarea.
The dart version should reflect this behavior.

**Comment by TedSander** [comment]
This is the design that our designers have given us. We are looking at design changes and the new one has the resize enabled, but this version won't.

**Comment by e-belair** [comment]
@TedSander do you know approximatively when this new version will be released?

**Comment by TedSander** [comment]
No sorry we aren't giving any timelines currently. Actively working getting it to work for internal clients first.
