### ISSUE TITLE
Not clear how to use material input

### ISSUE THREAD

**Issue by Timmmm** [dart-lang/angular_components#448]
This is one of the first things you'd want to do and it really isn't obvious how to do a basic binding to a `<material-input>`.

I did the same as in #24, and tried `[(inputText)]="foo"` and `[(ngModel)]="foo"`, neither of which give compilation errors, but also neither of which work!

So apparently out you need to add install `angular_forms`, add `formDirectives` to the list of directives. I did that, but then it gives me this error:

```
dir.valueAccessor != null
"No value accessor for () or you may be missing formDirectives in your directives list."
```

Wait... *I just added `formDirectives` to my directives list!!!*

Ok let me Google error number 15.... [aha](https://stackoverflow.com/questions/51297778/angular-forms-no-value-accessor-for/51310512). You have to use `materialInputDirectives` instead of `MaterialButtonComponent`.

It finally works! Please can you update [this page](https://dart-lang.github.io/angular_components/#/material_input) with at least some bare minimum "how to" like this:

> To use use `<material-input>` you should install the `angular_forms` package, then `import 'package:angular_forms/angular_forms.dart';` add `materialInputDirectives` to your components directive lists (do not add `MaterialInputComponent` directly), and finally use `<material-input [(ngModel)]="field">` in your HTML, where `field` is a member of your component class.

**Comment by TedSander** [comment]
That is specifically what the SOURCE link and the examples are for.... We don't want to put all the code in the doc comment itself.

**Comment by Timmmm** [comment]
I mean... yeah that's how I eventually worked it out, but it wasn't nearly as easy as if that paragraph were in the actual docs. I'm not sure I would call "read the source" good documentation. Up to you though I guess.
