### ISSUE TITLE
Please update to support dart 2.9.0-5.0.dev

### ISSUE THREAD

**Issue by insinfo** [dart-lang/angular_components#464]
Please update to support dart 2.9.0-5.0.dev

due to this https://github.com/dart-lang/angular/issues/1891
  problem I had to upgrade to dart 2.9 Angular 6 is working correctly without angular_components
Due to this

Because observable> = 0.1.1 <= 0.22.1 + 3 requires SDK version <2.0.0 or> = 2.0.0-dev.23.0 <2.0.0 and angular_components> = 0.9.0-beta + 1 <0.13.0 depends on observable ^ 0.22.1 + 3, angular_components> = 0.9.0-beta + 1 <0.13.0 requires observable ^ 0.22.1 + 4.
And because angular_components <0.9.0-beta + 1 requires SDK version> = 1.22.0 <2.0.0-∞, angular_components <0.13.0 requires observable ^ 0.22.1 + 4.
And because angular_components> = 0.13.0 depends on observable ^ 0.22.2 which depends on dart_internal ^ 0.1.1, every version of angular_components requires dart_internal ^ 0.1.1.
So, because dart_internal> = 0.1.1 requires SDK version> = 2.0.0-dev.12.0 <2.9.0 and angular_form_bug depends on angular_components any, version solving failed.

**Comment by p554157atch** [comment]
Any information on when the next sync will be available?

**Comment by kevmoo** [comment]
Update has shipped
