### ISSUE TITLE
material-input doesn't work with pageloader package

### ISSUE THREAD

**Issue by Kleak** [dart-lang/angular_components#64]
Here is a [sample](https://github.com/sestegra/angular2_components_test) of what i try to do everything work except one thing.
The `PageLoaderElement` `type` method doesn't work on the material-input component.

The value of `username` and `password` are not modified.
Do you have any idea why this doesn't work ?

**Comment by nshahan** [comment]
Try targeting the input elements that are inside a material-input element and type text into them.

**Comment by Kleak** [comment]
I have already try and same problem the username and password variable are also null

**Comment by nshahan** [comment]
My next guess is that the DOM isn't stable yet when you click the button. Try adding `await fixture.update();` after you type in the input boxes and before you click.

**Comment by Kleak** [comment]
`fixture.update();` doesn't solve the problem.
[here](https://github.com/Kleak/angular2_components_test) I have username and password well filled dunno if it should be done like that, if you have suggestion i'm open.

**Comment by nshahan** [comment]
I made a few edits and I think it is working. Take a look here https://github.com/nshahan/angular2_components_test/tree/tests

**Comment by Kleak** [comment]
great thanks a lot @nshahan

**Comment by nshahan** [comment]
Is it OK to close this issue?
