### ISSUE TITLE
Make Disposable utilities public

### ISSUE THREAD

**Issue by eredo** [dart-lang/angular_components#69]
I have seen the pattern of disposables in google closure library before and I think it's a great way to cleanup things. We're already using the `Disposable` interface as well as the `Disposer` implementation of `angular2_components` and I would like to know if it's already stable. If so, would it be possible to provide it as a public api (ex: `package:angular2_components/disposable.dart` or in generell `package:angular2_components/utils.dart`), since it's not best practice to include `package:../src/...` files.

**Comment by nshahan** [comment]
Thanks for the feedback! I am working on some repo management stuff that will unblock me. I want to expose more files (move them from `lib/src` to `lib`) so that you can import them in good faith.

**Comment by nshahan** [comment]
All the files considered to be entry points were moved out of the lib/src/ directory for the 0.8.0 release.
