### ISSUE TITLE
Could material-dropdown-select implement floatingLabel?

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular_components#71]
`material-dropdown-select` looks inconsistent in my forms as my other elements utilise `floatingLabel`. Also it feels awkward having to update the UI on selection by updating `buttonText`.

Would it not be more consistent to rename `buttonText` as `label`, make it automatically update to show selection also support `floatingLabel` which would allow the user to see both the label and their `selection`?

**Comment by nshahan** [comment]
This is helpful feedback. I'll take a look at the spec to see where there is room to make the appearance more consistent.

**Comment by sturmf** [comment]
Hi, I independently had the same issue but did not know about this issue. I reported my question here:
 https://stackoverflow.com/questions/44270472/how-to-add-floating-label-on-top-of-angular-dart-material-dropdown-select

So this might show that there is interest in this feature.

**Comment by nshahan** [comment]
I don't see an example of this in the Material Design spec.

**Comment by dani-gallegos** [comment]
I think you can see an example in the Material Design spec [here](https://material.io/guidelines/components/text-fields.html#text-fields-layout)

In the section with the title "Dropdown icon".

It's also implemented in the angular material components for [typescript](https://material.angular.io/components/select/overview)

Thanks in advance,
