### ISSUE TITLE
MaterialExpansionPanelSet add `get contentVisible` field

### ISSUE THREAD

**Issue by kostaa** [dart-lang/angular_components#89]
I have a FAB that adds a new model/panel to a `<material-expansionpanel-set>`. This button should be dissabled when one of the panels is opened and enabled when all panels are closed. So it would be good to have a stream for the panel events. Something similar to the `LazyEventEmitter<bool> get contentVisible` that is on the `<material-expansionpanel>`. 

Seems like a pretty straighforward change as it can work off the `_openPanel`  field.

**Comment by kostaa** [comment]
Would you accept a PR for this?

**Comment by nshahan** [comment]
Sorry, we currently don't have the infrastructure in place to merge a PR. I'll discuss with the internal owner of the exansionpanel and see if supporting these events would be a good fit.

**Comment by phantomesse** [comment]
Hi! I'm the internal owner of the expansion panel.

I want to make sure that I understand your use case here. From what I've gathered, you would like an `@Output` from the `<material-expansionpanel-set>` that tells you whether a `<material-expansionpanel>` within the set is expanded. I haven't received any requests for this feature internally.

In the use cases that I've seen, when you're using the `<material-expansionpanel-set>`, the `<material-expansionpanel>` are within scope. It would look something like this:

```
<material-expansionpanel-set>
    <material-expansionpanel></material-expansionpanel>
    <material-expansionpanel></material-expansionpanel>
    <material-expansionpanel></material-expansionpanel>
</material-expansionpanel-set>
```

To check whether any of the `<material-expansionpanel>`s within the set are open, you can listen for the `@Output` `(expandedChange)`. Here is an example:

```
@Component(
    selector: 'my-awesome-component',
    directives: const [
      MaterialExpansionPanel,
      MaterialExpansionPanelSet,
    ],
    template: '''
      <span>{{panelExpandedMessage}}</span>
    
      <material-expansionpanel-set>
        <material-expansionpanel
          (expandedChange)="isOnePanelExpanded = \$event">
        </material-expansionpanel>
        <material-expansionpanel
          (expandedChange)="isOnePanelExpanded = \$event">
        </material-expansionpanel>
        <material-expansionpanel
          (expandedChange)="isOnePanelExpanded = \$event">
        </material-expansionpanel>
      </material-expansionpanel-set>      
    ''')
class MyAwesomeComponent {
  bool isOnePanelExpanded = false;
  String get panelExpandedMessage => isOnePanelExpanded
      ? 'There is an expanded panel!'
      : 'No panels are expanded.';
}
```

And if you have a ton of `<material-expansionpanel>`s, you can do this:
```
@Component(
    selector: 'my-second-awesome-component',
    directives: const [
      MaterialExpansionPanel,
      MaterialExpansionPanelSet,
    ],
    template: '''
      <span>{{panelExpandedMessage}}</span>
    
      <material-expansionpanel-set>
        <material-expansionpanel></material-expansionpanel>
        <material-expansionpanel></material-expansionpanel>
        <material-expansionpanel></material-expansionpanel>
        <material-expansionpanel></material-expansionpanel>
        <material-expansionpanel></material-expansionpanel>
        <material-expansionpanel></material-expansionpanel>
        <material-expansionpanel></material-expansionpanel>
        <material-expansionpanel></material-expansionpanel>
        <material-expansionpanel></material-expansionpanel>
        <material-expansionpanel></material-expansionpanel>
      </material-expansionpanel-set>      
    ''')
class MySecondAwesomeComponent {
  bool isOnePanelExpanded = false;
  String get panelExpandedMessage => isOnePanelExpanded
      ? 'There is an expanded panel!'
      : 'No panels are expanded.';

  @ViewChildren(MaterialExpansionPanel)
  set panels(QueryList<MaterialExpansionPanel> panels) {
    panels.forEach((panel) {
      panel.isExpandedChange.listen((isPanelExpanded) {
        isOnePanelExpanded = isPanelExpanded;
      });
    });
  }
}
```

Please let me know if listening to `(expandedChange)` from the `<material-expansionpanel>` works for your use case.

**Comment by kostaa** [comment]
Hi phantomesse, the second example is exactly what I need so thanks for that.  I have a couple of related questions if you do not mind. 

The panel opens/closes quite fast. Is there a way to add a transition effect on the panel to make the opening and closing a bit more 'elegant'?

I am adding panels into the set to dynamically.  There is a FAB that allows to add a new panel and then the user fills in the form that is inside the panel. The issue I have is that I need to delete panels as well but not sure what is the best way to do it. One thought I had was to add a third 'delete' button to each panel but it does not seem to be possible. Is there a 'recommended' way of deleting panels from the set?

**Comment by phantomesse** [comment]
Hi kostaa,

So sorry for the delayed response! I realized that I wasn't getting notifications on this issue.

There is currently a transition for the expand/collapse for the panel, and the transition is in accordance with the material design spec.

There isn't a recommended way of deleting expansion panels from a set. You can customize the expansion panel's toolbelt and add a "delete" button there using the <toolbelt> ng-content: https://github.com/dart-lang/angular_components/blob/master/lib/src/components/material_expansionpanel/material_expansionpanel.html#L59

Please let me know if you have any further issues! I'm going to make sure that I get emailed when this issue is updated.
