### ISSUE TITLE
MaterialDropdownSelectComponent disable unselect

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_components#94]
Currently when I click on the selected item in a MaterialDropdownSelectComponent, the item becomes unselected. 
Is there an easy way to prevent deselection and only allow to select an item?

**Comment by cissyshi** [comment]
You can use the RadioGroupSingleSelectionModel class as your selection model which prevents deselection.

**Comment by zoechi** [comment]
@cissyshi Thanks! Sound's like what I'm looking for. Will try and report back.

**Comment by zoechi** [comment]
@cissyshi works like a charm. Thanks a lot.

**Comment by nbro** [comment]
To ease the process of understanding how to use the suggested solution above, I would like first to point you to the documentation for `RadioGroupSingleSelectionModel`

> https://webdev.dartlang.org/api/angular_components/angular_components/RadioGroupSingleSelectionModel/RadioGroupSingleSelectionModel

Its constructor accepts an initial value, so we can create a `RadioGroupSingleSelectionModel` object like

```
final RadioGroupSingleSelectionModel<String> mySelectModel =
    new RadioGroupSingleSelectionModel<String>(myInitialValue);
```
